-- Run once in a fresh Supabase project's SQL editor.
create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users on delete cascade,name text not null,role text not null check(role in ('student','teacher')),created_at timestamptz default now());
create function public.create_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,name,role) values(new.id,left(coalesce(new.raw_user_meta_data->>'name','Learner'),80),case when new.raw_user_meta_data->>'role'='teacher' then 'teacher' else 'student' end); return new; end $$;
create trigger on_user_created after insert on auth.users for each row execute function public.create_profile();
create table public.classes(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references profiles, name text not null,join_code text unique not null default encode(gen_random_bytes(6),'hex'),created_at timestamptz default now());
create table public.enrollments(class_id uuid references classes on delete cascade,student_id uuid references profiles on delete cascade,primary key(class_id,student_id));
create table public.assignments(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references profiles,class_id uuid not null references classes on delete cascade,title text not null,mission_id text not null,objectives text not null default '',due_at timestamptz,status text not null check(status in ('draft','published')),created_at timestamptz default now());
create table public.learning_sessions(id uuid primary key default gen_random_uuid(),student_id uuid not null references profiles on delete cascade,mission_id text,topic text,assignment_id uuid references assignments on delete set null,state jsonb not null default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.attempts(id uuid primary key default gen_random_uuid(),student_id uuid not null references profiles on delete cascade,session_id uuid not null unique references learning_sessions on delete cascade,assignment_id uuid references assignments on delete set null,mission_id text,report jsonb not null,score numeric not null check(score between 0 and 100),xp integer not null default 0,teacher_feedback text,teacher_score numeric check(teacher_score between 0 and 100),created_at timestamptz default now());
create unique index one_mission_reward on public.attempts(student_id,mission_id) where mission_id is not null and xp>0;
create table public.ai_usage(id bigint generated always as identity primary key,user_id uuid not null references profiles on delete cascade,created_at timestamptz default now());
create index ai_usage_user_time on ai_usage(user_id,created_at);
create function public.consume_ai_budget() returns boolean language plpgsql security definer set search_path=public as $$ begin perform pg_advisory_xact_lock(hashtext(auth.uid()::text)); if auth.uid() is null then return false; end if; if (select count(*) from ai_usage where user_id=auth.uid() and created_at>now()-interval '1 minute')>=12 or (select count(*) from ai_usage where user_id=auth.uid() and created_at>now()-interval '1 day')>=200 then return false; end if; insert into ai_usage(user_id) values(auth.uid()); return true; end $$;
create function public.teaches(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from classes where id=cid and teacher_id=auth.uid()) $$;
create function public.enrolled(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from enrollments where class_id=cid and student_id=auth.uid()) $$;
create function public.can_review(aid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from assignments where id=aid and teacher_id=auth.uid()) $$;
create function public.join_class(code text) returns void language plpgsql security definer set search_path=public as $$ declare cid uuid; begin if not exists(select 1 from profiles where id=auth.uid() and role='student') then raise exception 'Student account required'; end if; select id into cid from classes where join_code=lower(trim(code)); if cid is null then raise exception 'Invalid class code'; end if; insert into enrollments values(cid,auth.uid()) on conflict do nothing; end $$;
alter table profiles enable row level security;
alter table classes enable row level security;
alter table enrollments enable row level security;
alter table assignments enable row level security;
alter table learning_sessions enable row level security;
alter table attempts enable row level security;
alter table ai_usage enable row level security;
create policy profile_read on profiles for select to authenticated using(id=auth.uid() or exists(select 1 from enrollments e where e.student_id=profiles.id and teaches(e.class_id)));
create policy class_read on classes for select to authenticated using(teacher_id=auth.uid() or enrolled(id));
create policy class_create on classes for insert to authenticated with check(teacher_id=auth.uid() and exists(select 1 from profiles where id=auth.uid() and role='teacher'));
create policy enrollment_read on enrollments for select to authenticated using(student_id=auth.uid() or teaches(class_id));
create policy assignment_read on assignments for select to authenticated using(teacher_id=auth.uid() or (status='published' and enrolled(class_id)));
create policy assignment_create on assignments for insert to authenticated with check(teacher_id=auth.uid() and teaches(class_id));
create policy assignment_edit on assignments for update to authenticated using(teacher_id=auth.uid()) with check(teacher_id=auth.uid() and teaches(class_id));
create policy session_read on learning_sessions for select to authenticated using(student_id=auth.uid() or can_review(assignment_id));
create policy session_create on learning_sessions for insert to authenticated with check(student_id=auth.uid() and (assignment_id is null or exists(select 1 from assignments where id=assignment_id and status='published' and enrolled(class_id))));
create policy session_edit on learning_sessions for update to authenticated using(student_id=auth.uid()) with check(student_id=auth.uid() and (assignment_id is null or exists(select 1 from assignments where id=assignment_id and status='published' and enrolled(class_id))));
create policy attempts_read on attempts for select to authenticated using(student_id=auth.uid() or can_review(assignment_id));
-- Attempts are written only by the server with the service role after evaluating saved work.
revoke all on all tables in schema public from anon;
grant select on profiles,classes,enrollments,assignments,learning_sessions,attempts to authenticated;
grant insert on classes,assignments,learning_sessions to authenticated;
grant update on assignments,learning_sessions to authenticated;
revoke all on function public.create_profile() from public;
revoke all on function public.join_class(text),public.consume_ai_budget(),public.teaches(uuid),public.enrolled(uuid),public.can_review(uuid) from public;
grant execute on function public.join_class(text),public.consume_ai_budget(),public.teaches(uuid),public.enrolled(uuid),public.can_review(uuid) to authenticated;
