import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import {pathToFileURL} from "node:url";
const temp=await fs.mkdtemp(path.join(process.cwd(),".nova-tests-connected-"));
const names=["content-integrity","curriculum-audit","learning-domain","course-domain","course-sample","course-compiler","assessment-engine","learning-content","socratic","evidence"];
for(const name of names){let source=await fs.readFile(`lib/novalearn/${name}.ts`,"utf8");for(const dep of names)source=source.replaceAll(`"./${dep}"`,`"./${dep}.mjs"`);await fs.writeFile(path.join(temp,`${name}.mjs`),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const load=name=>import(pathToFileURL(path.join(temp,`${name}.mjs`)).href);
const C=await load("learning-content"),I=await load("content-integrity"),A=await load("assessment-engine"),D=await load("course-domain"),S=await load("socratic"),E=await load("evidence"),R=await load("curriculum-audit"),P=await load("course-compiler"),{sampleCourse,sampleDemonstrations}=await load("course-sample");
function draft(){const d=sampleCourse().data;d.chapters=C.deriveChapters(d);return d;}
async function generated(){const d=draft();d.chapters[0]=await C.generateChapter(d,d.chapters[0].id);return d;}
const input=d=>({moduleId:d.modules[0].id,objectiveIds:d.modules[0].objectiveIds,category:"Assignment",format:"Case study",emphasis:"Apply the approved curriculum and defend your reasoning.",duration:60,difficulty:"Core",verification:"Standard",aiPolicy:"Planning only; disclose use",collaboration:"Individual",resources:"Approved chapter",knowledgeQuestions:1});
function demonstration(){const d=sampleDemonstrations(sampleCourse())[0];d.status="draft";d.data.questions=[];d.data.evidence=[];d.data.evaluation=null;d.data.review=null;E.saveAnswers(d,{artifact:"My proposed solution uses source-grounded retrieval and tests its assumptions.",explanation:"I distinguish retrieval similarity from factual support and verify the source scope before answering."});return d;}
function answers(d){return {artifact:d.data.evidence.find(e=>e.kind==="artifact")?.answer||"",explanation:d.data.evidence.find(e=>e.kind==="explanation")?.answer||"",followupAnswers:Object.fromEntries(d.data.questions.map(q=>[q.id,d.data.evidence.find(e=>e.id===q.id)?.answer||"I would test this claim against the cited source and compare a counterexample before deciding."])),transfer:"With the changed constraint, I compare an alternative approach and explain why its assumptions still hold.",disclosure:"No AI assistance",reflection:"I learned that a plausible match is not sufficient evidence of truth."};}

test("legacy records remain valid and chapter derivation preserves module identities",()=>{const old=sampleCourse().data;D.courseDataSchema.parse(old);const d=draft();assert.equal(d.chapters.length,d.modules.length);assert.deepEqual(d.modules,old.modules);assert.deepEqual(C.deriveChapters(d),d.chapters);assert.deepEqual(d.chapters[0].objectiveIds,d.modules[0].objectiveIds);assert.throws(()=>C.deriveChapters({...d,graphApproved:false}),/Approve/);});
test("chapter demo is source-derived, explicitly labeled and unapproved",async()=>{const d=await generated(),ch=d.chapters[0];assert.equal(ch.generation.mode,"demo");assert.equal(ch.status,"draft");assert.ok(ch.blocks.some(b=>b.kind==="reference"));assert.deepEqual(C.contentIssues(d,ch),[]);D.courseDataSchema.parse(d);});
test("chapter generation requires approved graph and relevant approved sources",async()=>{const d=draft();await assert.rejects(C.generateChapter({...d,graphApproved:false},d.chapters[0].id),/Approve/);await assert.rejects(C.generateChapter({...d,sources:[]},d.chapters[0].id),/source/);});
test("model output cannot invent citations or curriculum objective IDs",async()=>{const d=await generated(),ch=d.chapters[0],bad=structuredClone(ch.blocks);bad[0].sourceIds=["invented"];await assert.rejects(C.generateChapter(d,ch.id,async()=>({value:{blocks:bad},routing:"test"})),/retrieval context/);bad[0]=structuredClone(ch.blocks[0]);bad[0].objectiveIds=["invented"];await assert.rejects(C.generateChapter(d,ch.id,async()=>({value:{blocks:bad},routing:"test"})),/objective/);});
test("critic failure leaves the saved chapter untouched",async()=>{const d=await generated(),before=JSON.stringify(d),ch=d.chapters[0];await assert.rejects(C.generateChapter(d,ch.id,async()=>({value:{blocks:ch.blocks},routing:"test draft"}),async()=>({value:{issues:["Unsupported conclusion"],notes:[]},routing:"test judge"})),/Unsupported/);assert.equal(JSON.stringify(d),before);});
test("professor approval and publication expose only released current chapters",async()=>{const d=await generated();d.chapters[0]=C.approveChapter(d,d.chapters[0].id);assert.ok(I.approvedChapter(d,d.chapters[0]));const p=D.publishable({...sampleCourse(),data:d});assert.equal(p.chapters.length,1);assert.equal(p.chapters[0].generation,undefined);d.learning.releasedModuleIds=[];assert.equal(D.publishable({...sampleCourse(),data:d}).chapters.length,0);});
test("editing a source invalidates chapter and legacy material approval",async()=>{const old=await generated();old.chapters[0]=C.approveChapter(old,old.chapters[0].id);const d=structuredClone(old);d.sources[0].chunks[0].text+=" Changed authoritative context.";I.reconcileContent(d,old);assert.equal(d.chapters[0].status,"stale");assert.equal(d.chapters[0].approvedFingerprint,undefined);assert.equal(d.materials[0].approved,false);assert.equal(D.publishable({...sampleCourse(),data:d}).chapters.length,0);});
test("generic save cannot forge approval; locked chapter requires explicit unlock",async()=>{const old=await generated(),d=structuredClone(old);d.chapters[0].status="approved";d.chapters[0].approvedFingerprint=I.chapterFingerprint(d.chapters[0]);I.reconcileContent(d,old);assert.equal(d.chapters[0].status,"draft");old.chapters[0].locked=true;const edited=structuredClone(old);edited.chapters[0].locked=false;edited.chapters[0].blocks[0].text="Changed";assert.throws(()=>I.reconcileContent(edited,old),/Unlock/);await assert.rejects(C.generateChapter(old,old.chapters[0].id),/Unlock/);});
test("stale chapter outline can be explicitly refreshed from current blueprint",async()=>{const d=await generated(),id=d.chapters[0].id;d.modules[0].concepts=["Updated retrieval concept"];const ch=C.refreshChapterOutline(d,id);assert.equal(ch.id,id);assert.equal(ch.topics[0].title,"Updated retrieval concept");assert.equal(ch.blocks.length,0);assert.equal(ch.status,"outline");assert.ok(I.currentChapter(d,ch));});
test("released chapter cites only selected chunks from an otherwise private source",async()=>{const d=await generated();delete d.sources[0].moduleIds;d.sources[0].chunks.push({id:"private-chunk",text:"PRIVATE future chapter teaching"});d.chapters[0]=await C.generateChapter(d,d.chapters[0].id);d.chapters[0]=C.approveChapter(d,d.chapters[0].id);d.learning.releasedModuleIds=[d.modules[0].id];const p=D.publishable({...sampleCourse(),data:d});assert.equal(p.chapters.length,1);assert.ok(p.sources.length);assert.ok(!JSON.stringify(p.sources).includes("PRIVATE"));assert.ok(p.chapters[0].sourceIds.every(id=>p.sources.some(s=>s.chunks.some(c=>c.id===id))));});
test("content gate rejects missing alternatives, invalid graph edges, duplicate blocks and overload",async()=>{const d=await generated(),ch=structuredClone(d.chapters[0]);ch.blocks[0].kind="diagram";ch.blocks[0].nodes=[{id:"a",label:"A"}];ch.blocks[0].edges=[{from:"a",to:"missing"}];ch.blocks.push(ch.blocks[0]);const issues=C.contentIssues(d,ch).join(" ");assert.match(issues,/unique/);assert.match(issues,/alternative/);assert.match(issues,/edges/);});
test("assessment context consumes approved content and refreshes after chapter edits",async()=>{const d=await generated();assert.equal(A.assessmentContext(d,input(d)).learningContent.blocks.length,0);d.chapters[0]=C.approveChapter(d,d.chapters[0].id);const ctx=A.assessmentContext(d,input(d));assert.ok(ctx.learningContent.blocks.length);d.assessmentDesigns=[A.createAssessmentDesign(d,input(d),"design","assessment")];const before=structuredClone(d);d.chapters[0].blocks[0].text+=" Professor correction";I.reconcileContent(d,before);A.reconcileAssessmentEdits(d,before);assert.notEqual(d.assessmentDesigns[0].contextFingerprint,before.assessmentDesigns[0].contextFingerprint);assert.equal(d.assessmentDesigns[0].log.length,0);});
test("compiler gap analysis is explicit and research queue is bounded",()=>{const d=draft();d.sources=[];const audit=R.curriculumAudit(d);assert.equal(audit.method,"lexical-and-structural-v1");assert.ok(audit.researchQuestions.length<=5);assert.ok(audit.researchQuestions.every(q=>q.status==="proposed"));assert.ok(audit.coverage.every(c=>!c.sourceIds.length));});
test("compiler pauses expensive downstream generation for professor approval",async()=>{let d=D.blankCourse();d.syllabus="Information retrieval\nEvaluating evidence\nDesigning grounded answers";d.compiler={inputs:{...P.defaultInputs(d),code:"CS381",intent:"Students apply retrieval techniques and verify supporting evidence.",moduleCount:3,checkpointCount:2},sourceMap:[],schedule:[],log:[],reviewed:false};for(const key of ["intent","sources","constraints","graph","planner"])d=await P.runCompilerJob(d,key);let calls=0;await assert.rejects(P.runCompilerJob(d,P.nextCompilerJob(d).key,async()=>{calls++;return {value:{},routing:"test"};}),/approve/);assert.equal(calls,0);});
test("stateful dialogue saves one probe, waits for evidence, then stops at configured limit",async()=>{let d=demonstration();for(let n=0;n<3;n++){d=await S.advanceDialogue(d);assert.equal(d.data.questions.length,n+1);assert.equal(d.data.dialogue.status,"active");await assert.rejects(S.advanceDialogue(d),/pending/);E.saveAnswers(d,answers(d));}d=await S.advanceDialogue(d);assert.equal(d.data.dialogue.status,"complete");assert.match(d.data.dialogue.reason,/limit/);assert.equal(d.data.dialogue.mode,"demo");assert.equal(d.data.evaluation,null);D.canSubmit(d);});
test("live dialogue may stop on sufficient evidence after a grounded probe",async()=>{let d=await S.advanceDialogue(demonstration());E.saveAnswers(d,answers(d));d=await S.advanceDialogue(d,async()=>({value:{sufficient:true,reason:"Every objective now has evidence for professor review.",uncertainty:"",objectiveIds:d.snapshot.checkpoint.objectiveIds,evidenceIds:d.data.evidence.map(e=>e.id).filter(id=>!["transfer","reflection"].includes(id))},routing:"test"}));assert.equal(d.data.dialogue.status,"complete");assert.equal(d.data.evaluation,null);});
test("dialogue rejects invented evidence and repeated questions atomically",async()=>{const original=demonstration();await assert.rejects(S.advanceDialogue(original,async()=>({value:{sufficient:false,reason:"Probe an unsupported claim in the student's explanation.",uncertainty:"Claim lacks source support",objectiveIds:original.snapshot.checkpoint.objectiveIds,evidenceIds:["missing"],question:"What supports this particular claim?"},routing:"test"})),/invalid/);assert.equal(original.data.dialogue,undefined);});
test("changed earlier answer removes only dependent probes and reopens defense",async()=>{let d=await S.advanceDialogue(demonstration());E.saveAnswers(d,answers(d));d=await S.advanceDialogue(d);E.saveAnswers(d,answers(d));const form=answers(d);form.followupAnswers[d.data.questions[0].id]="I revised the assumption after checking a conflicting source.";E.saveAnswers(d,form);assert.equal(d.data.questions.length,1);assert.equal(d.data.dialogue.status,"active");assert.ok(!d.data.evidence.some(e=>e.id==="socratic-2"));assert.throws(()=>D.canSubmit(d),/Socratic/);});
test("complete connected demo reaches professor insight without fabricating mastery",async()=>{const d=await generated();d.chapters[0]=C.approveChapter(d,d.chapters[0].id);d.assessmentDesigns=[A.createAssessmentDesign(d,input(d),"design","assessment")];let data=d;for(const stage of A.assessmentStages)data=await A.runAssessmentStage(data,"design",stage.key);data=A.approveAssessment(data,"design");const course={...sampleCourse(),data};const published=D.publishable(course);assert.ok(published.chapters.length);assert.ok(published.checkpoints.some(c=>c.id==="assessment"));let demo=demonstration();demo.snapshot.checkpoint=published.checkpoints.find(c=>c.id==="assessment");demo.snapshot.objectives=published.objectives.filter(o=>demo.snapshot.checkpoint.objectiveIds.includes(o.id));demo.data.questions=[];demo.data.evidence=[];E.saveAnswers(demo,{artifact:"I applied retrieval with a documented source-grounding procedure.",explanation:"I verified source scope and distinguished high similarity from actual support for the claim."});for(let n=0;n<3;n++){demo=await S.advanceDialogue(demo);E.saveAnswers(demo,answers(demo));}demo=await S.advanceDialogue(demo);D.canSubmit(demo);demo.status="submitted";demo.course_id=course.id;demo.data.evaluation=D.validateEvaluation({summary:"Requires human verification",findings:demo.snapshot.checkpoint.objectiveIds.map(objectiveId=>({objectiveId,level:"Developing",confidence:"Low",rationale:"Review the cited reasoning evidence.",evidenceIds:["explanation"],uncertainty:"Live evaluator not exercised"})),misconceptions:[],nextSteps:["Professor reviews the reasoning trail."]},demo);assert.ok(D.courseInsights(course,[demo]).some(row=>row.Developing>0));});
test.after(async()=>{await fs.rm(temp,{recursive:true,force:true});});
