import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import {pathToFileURL} from "node:url";
const temp=await fs.mkdtemp(path.join(process.cwd(),".nova-tests-assessment-"));
const names=["content-integrity","curriculum-audit","learning-domain","course-domain","course-sample","assessment-engine","course-compiler","evidence"];
for(const name of names){let source=await fs.readFile(`lib/novalearn/${name}.ts`,"utf8");for(const dep of names)source=source.replaceAll(`"./${dep}"`,`"./${dep}.mjs"`);await fs.writeFile(path.join(temp,`${name}.mjs`),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const load=name=>import(pathToFileURL(path.join(temp,`${name}.mjs`)).href);
const E=await load("assessment-engine"),D=await load("course-domain"),{sampleCourse}=await load("course-sample");
function input(d){return {moduleId:d.modules[0].id,objectiveIds:d.modules[0].objectiveIds,category:"Assignment",format:"Case study",emphasis:"Apply concepts and explain decisions with concrete evidence.",duration:60,difficulty:"Core",verification:"Extended",aiPolicy:"Planning only; disclose use",collaboration:"Individual",resources:"Approved course sources",knowledgeQuestions:1};}
function start(){const d=sampleCourse().data;d.assessmentDesigns=[E.createAssessmentDesign(d,input(d),"design-1","auth-1")];return d;}
async function finish(d=start()){for(let i=0;i<6;i++){const s=E.nextAssessmentStage(d.assessmentDesigns[0]);if(s)d=await E.runAssessmentStage(d,"design-1",s.key);}return d;}
test("six stages produce complete structured package without publishing",async()=>{const d=await finish(),a=d.assessmentDesigns[0];D.courseDataSchema.parse(d);assert.equal(a.log.length,6);assert.equal(E.nextAssessmentStage(a),undefined);assert.deepEqual(E.assessmentIssues(d,a),[]);assert.equal(a.approvedFingerprint,undefined);assert.ok(!d.checkpoints.some(c=>c.id==="auth-1"));});
test("professor approval creates a compatible checkpoint and preserves existing data",async()=>{const before=start(),d=await finish(before);E.approveAssessment(d,"design-1");assert.equal(d.checkpoints.length,before.checkpoints.length+1);assert.deepEqual(d.checkpoints[0],before.checkpoints[0]);assert.deepEqual(d.modules,before.modules);assert.deepEqual(d.learning,before.learning);E.validateAuthenticPublication(d);});
test("publication excludes every private guide, log and design fingerprint",async()=>{const d=await finish();E.approveAssessment(d,"design-1");const p=D.publishable({...sampleCourse(),data:d});const text=JSON.stringify(p);assert.equal(p.assessmentDesigns,undefined);assert.ok(!text.includes("privateGuide"));assert.ok(!text.includes("expectedReasoning"));assert.ok(p.checkpoints.find(c=>c.id==="auth-1").authentic.tasks.length);});
test("private guide is retrieved from a frozen release, not a mutable current design",async()=>{const d=await finish();E.approveAssessment(d,"design-1");const frozen=structuredClone(d),cp=E.assessmentCheckpoint(d.assessmentDesigns[0]);d.assessmentDesigns[0].verification.privateGuide[0].expectedReasoning="Changed later";assert.notEqual(E.privateAssessmentGuide(frozen,cp)[0].expectedReasoning,"Changed later");});
test("rejects unknown IDs, excessive recall counts and cross-module scope",()=>{const d=start();assert.throws(()=>E.validateAssessmentInput(d,{...input(d),objectiveIds:["missing"]}),/objectives/);assert.throws(()=>E.validateAssessmentInput(d,{...input(d),knowledgeQuestions:6}));assert.throws(()=>E.validateAssessmentInput({...d,graphApproved:false},input(d)),/Approve/);});
test("failed provider call is atomic and never mutates saved design",async()=>{const d=start(),before=JSON.stringify(d);await assert.rejects(E.runAssessmentStage(d,"design-1","evidence",async()=>{throw new Error("Quota unavailable");}),/Quota/);assert.equal(JSON.stringify(d),before);});
test("malformed model response is rejected before stage completion",async()=>{const d=start();await assert.rejects(E.runAssessmentStage(d,"design-1","evidence",async()=>({value:{evidence:[]},routing:"mock"})));assert.equal(d.assessmentDesigns[0].log.length,0);});
test("cannot run out of sequence or repeat a completed stage",async()=>{const d=start();await assert.rejects(E.runAssessmentStage(d,"design-1","task"),/stage changed/);const done=await E.runAssessmentStage(d,"design-1","evidence");await assert.rejects(E.runAssessmentStage(done,"design-1","evidence"),/stage changed/);});
test("routing makes exactly six targeted calls with stronger task/rubric checks",async()=>{let d=start();const calls=[];for(const stage of E.assessmentStages){const template=await E.runAssessmentStage(d,"design-1",stage.key);const output=template.assessmentDesigns[0][stage.key];d=await E.runAssessmentStage(d,"design-1",stage.key,async(tier)=>{calls.push(tier);return {value:stage.key==="evidence"?{evidence:output}:output,routing:"mock model"};});}assert.deepEqual(calls,["draft","draft","judge","judge","judge","judge"]);});
test("rubric totals, task workload, objective coverage and citations block approval",async()=>{const d=await finish(),a=d.assessmentDesigns[0];a.scoring.rubric[0].weight=1;a.task.tasks[0].minutes=600;a.task.sourceIds=["fake-source"];a.task.tasks[0].kind="Knowledge";const issues=E.assessmentIssues(d,a).join(" ");assert.match(issues,/100%/);assert.match(issues,/budget/);assert.match(issues,/source/);assert.match(issues,/applied task/);assert.throws(()=>E.approveAssessment(d,a.id));});
test("model alignment blockers require repair and revalidation",async()=>{let d=await finish();d.assessmentDesigns[0]=E.resetAssessmentFrom(d.assessmentDesigns[0],"alignment");d=await E.runAssessmentStage(d,"design-1","alignment",async()=>({value:{summary:"Needs work",issues:["Variant is harder than the original"]},routing:"mock"}));assert.match(E.assessmentIssues(d,d.assessmentDesigns[0]).join(" "),/Variant/);assert.throws(()=>E.approveAssessment(d,"design-1"));});
test("regeneration preserves prior stages and removes only dependent outputs",async()=>{const d=await finish(),a=d.assessmentDesigns[0],reset=E.resetAssessmentFrom(a,"scoring");assert.deepEqual(reset.task,a.task);assert.deepEqual(reset.evidence,a.evidence);assert.equal(reset.scoring,undefined);assert.equal(reset.verification,undefined);assert.equal(reset.alignment,undefined);assert.equal(E.nextAssessmentStage(reset).key,"scoring");});
test("manual stage edits invalidate downstream outputs and approval",async()=>{const old=await finish();E.approveAssessment(old,"design-1");const d=structuredClone(old);d.assessmentDesigns[0].task.instructions+=" Explain a limitation.";E.reconcileAssessmentEdits(d,old);assert.equal(d.assessmentDesigns[0].scoring,undefined);assert.equal(d.assessmentDesigns[0].approvedFingerprint,undefined);assert.equal(d.checkpoints.find(c=>c.id==="auth-1").published,false);assert.equal(E.nextAssessmentStage(d.assessmentDesigns[0]).key,"scoring");});
test("changing professor inputs or source context resets the design",async()=>{const old=await finish(),d=structuredClone(old);d.assessmentDesigns[0].inputs.duration=90;E.reconcileAssessmentEdits(d,old);assert.equal(d.assessmentDesigns[0].task,undefined);const source=structuredClone(old);source.objectives[0].title+=" Revised";assert.ok(E.assessmentIssues(source,source.assessmentDesigns[0]).some(x=>x.includes("changed")));});
test("cannot forge approval through the general save reconciliation",async()=>{const old=await finish(),d=structuredClone(old);d.assessmentDesigns[0].approvedFingerprint=E.assessmentFingerprint(d.assessmentDesigns[0]);E.reconcileAssessmentEdits(d,old);assert.equal(d.assessmentDesigns[0].approvedFingerprint,undefined);});
test("legacy editor content changes cannot bypass the authentic release guard",async()=>{const d=await finish();E.approveAssessment(d,"design-1");d.checkpoints.find(c=>c.id==="auth-1").prompt+=" Changed requirements.";assert.throws(()=>E.validateAuthenticPublication(d),/outside its engine/);});
test("variants are deterministic, frozen per student and do not change rubric",async()=>{const d=await finish(),cp=E.assessmentCheckpoint(d.assessmentDesigns[0]);const a=E.assignAssessmentVariant(cp,"student-a"),b=E.assignAssessmentVariant(cp,"student-a");assert.deepEqual(a,b);assert.equal(a.authentic.variants.length,1);assert.deepEqual(a.rubric,cp.rubric);assert.equal(cp.authentic.assignedVariant,undefined);});
test("extended assessment requires reflection and transparent assistance disclosure",async()=>{const d=await finish(),cp=E.assessmentCheckpoint(d.assessmentDesigns[0]);const demo={snapshot:{checkpoint:cp},data:{evidence:[],questions:[],disclosure:""}};assert.throws(()=>D.canSubmit(demo),/reflection/);demo.data.evidence=[{kind:"reflection",answer:"I learned to check assumptions carefully."}];assert.throws(()=>D.canSubmit(demo),/Disclose/);});
test("old courses and checkpoints remain valid with no engine metadata",()=>{const c=sampleCourse();D.courseDataSchema.parse(c.data);E.validateAuthenticPublication(c.data);assert.equal(c.data.assessmentDesigns,undefined);});
test.after(async()=>{await fs.rm(temp,{recursive:true,force:true});});
