import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import { pathToFileURL } from "node:url";

const temp=await fs.mkdtemp(path.join(process.cwd(),".nova-tests-evidence-"));
const names=["learning-domain","content-integrity","course-domain","course-sample","student-evidence"];
for(const name of names){let source=await fs.readFile(`lib/novalearn/${name}.ts`,"utf8");for(const dep of names)source=source.replaceAll(`"./${dep}"`,`"./${dep}.mjs"`);await fs.writeFile(path.join(temp,`${name}.mjs`),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const load=name=>import(pathToFileURL(path.join(temp,`${name}.mjs`)).href);
const {sampleCourse,sampleDemonstrations}=await load("course-sample"), engine=await load("student-evidence");
function fixture(){const c=sampleCourse(),d=sampleDemonstrations(c)[0];d.status="draft";d.version=4;d.data.questions=[];d.data.evidence=[{id:"work",kind:"artifact",prompt:d.snapshot.checkpoint.prompt,answer:"I applied a grounded retrieval method to the case and checked the source before choosing a response.",objectiveIds:d.snapshot.checkpoint.objectiveIds,at:"2026-09-24T00:00:00Z"},{id:"reason",kind:"explanation",prompt:"Explain your reasoning",answer:"I selected the retrieval method because citation existence alone does not establish support for the claim.",objectiveIds:d.snapshot.checkpoint.objectiveIds,at:"2026-09-24T00:01:00Z"},{id:"transfer",kind:"transfer",prompt:d.snapshot.checkpoint.transferPrompt,answer:"With fewer documents I would check recall and justify any change to retrieval depth.",objectiveIds:d.snapshot.checkpoint.objectiveIds,at:"2026-09-24T00:02:00Z"}];d.data.helpUsed="";d.snapshot.evidenceLinks=engine.evidenceLinks(c.data,d.snapshot.checkpoint);return {c,d};}
function observation(t,input,status="SUPPORTED",kind){const wanted=kind||(t.id.endsWith("-reasoning")?"explanation":t.id.endsWith("-transfer")?"transfer":"artifact");const passage=input.passages.find(p=>p.kind===wanted)||input.passages[0];const quote=passage.answer.slice(0,40);return {targetId:t.id,status,claim:`The student's words explicitly address ${t.id}.`,strength:status==="SUPPORTED"?"STRONG":status==="PARTIALLY_SUPPORTED"?"MODERATE":status==="CONTRADICTED"?"CONTRADICTORY":"INSUFFICIENT",confidence:status==="AMBIGUOUS"?"LOW":"HIGH",supports:[{evidenceId:passage.id,start:0,end:quote.length,quote}]};}
function modelOf(overrides={}){return async(tier,_system,input)=>({routing:`test-${tier}`,value:{observations:input.assessment.criterion.map(t=>{const selected=overrides[t.id];return selected?selected(t,input):observation(t,input);})}});}

test("supported application, reasoning and transfer keep exact quote provenance",async()=>{const {c,d}=fixture();const result=await engine.evaluateStudentEvidence(d,c.data,modelOf());assert.equal(result.bundle.status,"evaluated");assert.equal(result.events.length,d.snapshot.checkpoint.objectiveIds.length*3);for(const e of result.events){assert.equal(e.status,"SUPPORTED");assert.equal(e.supports.length,1);const s=e.supports[0];assert.equal(d.data.evidence.find(x=>x.id===s.evidenceId).answer.slice(s.start,s.end),s.quote);assert.equal(e.assessmentId,d.checkpoint_id);assert.equal(e.studentId,d.student_id);assert.ok(e.expected&&e.criterion);}assert.ok(result.evaluation.findings.every(f=>f.level==="Strong"));});
test("artifact alone cannot establish reasoning even when marked correct",async()=>{const {d}=fixture();d.data.evidence=d.data.evidence.filter(e=>e.kind!=="explanation");const r=await engine.evaluateStudentEvidence(d,undefined,modelOf());assert.ok(r.events.some(e=>e.type==="APPLICATION"&&e.status==="SUPPORTED"));assert.ok(r.events.some(e=>e.type==="EXPLANATION"&&e.status==="NOT_OBSERVED"));assert.ok(r.evaluation.findings.every(f=>f.level==="Needs verification"));});
test("wrong artifact retains separately supported partial reasoning",async()=>{const {d}=fixture(),key=`${d.snapshot.checkpoint.objectiveIds[0]}-application`,reason=`${d.snapshot.checkpoint.objectiveIds[0]}-reasoning`;const r=await engine.evaluateStudentEvidence(d,undefined,modelOf({[key]:(t,i)=>observation(t,i,"CONTRADICTED"),[reason]:(t,i)=>observation(t,i,"PARTIALLY_SUPPORTED")}));assert.equal(r.events.find(e=>e.targetId===key).strength,"CONTRADICTORY");assert.equal(r.events.find(e=>e.targetId===reason).strength,"MODERATE");assert.equal(r.evaluation.findings[0].level,"Developing");});
test("misconception needs an objective-mapped concept and exact response span",async()=>{const {d}=fixture(),objective=d.snapshot.checkpoint.objectiveIds[0];d.snapshot.evidenceLinks.find(x=>x.objectiveId===objective).conceptIds=["mapped-concept"];const concept="mapped-concept",key=`${objective}-reasoning`,make=(id)=>modelOf({[key]:(t,i)=>{const o=observation(t,i,"CONTRADICTED");o.misconception={conceptId:id,statement:"The student treats any citation as sufficient proof.",support:o.supports[0]};return o;}});const good=await engine.evaluateStudentEvidence(d,undefined,make(concept));assert.equal(good.events.find(e=>e.targetId===key).misconception.conceptId,concept);const bad=await engine.evaluateStudentEvidence(d,undefined,make("invented-concept"));assert.equal(bad.bundle.status,"unavailable");assert.ok(bad.events.every(e=>e.status==="AMBIGUOUS"));});
test("ambiguous reasoning escalates and a later probe is retained separately",async()=>{const {d}=fixture(),key=`${d.snapshot.checkpoint.objectiveIds[0]}-reasoning`;let calls=0;const ask=async(tier,system,input)=>{calls++;return modelOf({[key]:(t,i)=>observation(t,i,"AMBIGUOUS")})(tier,system,input);};const first=await engine.evaluateStudentEvidence(d,undefined,ask);assert.equal(calls,2);assert.equal(first.events.find(e=>e.targetId===key).status,"AMBIGUOUS");d.version++;d.data.evidence.push({id:"probe",kind:"followup",prompt:"Which source supports that choice?",answer:"The approved source supports the diagnosis because it contrasts retrieval with generation failure.",at:"2026-09-24T00:03:00Z",objectiveIds:d.snapshot.checkpoint.objectiveIds});const after=await engine.evaluateStudentEvidence(d,undefined,modelOf({[key]:(t,i)=>observation(t,i,"SUPPORTED","followup")}));assert.notEqual(first.events.find(e=>e.targetId===key).id,after.events.find(e=>e.targetId===key).id);assert.equal([...first.events,...after.events].filter(e=>e.targetId===key).length,2);});
test("failed escalation preserves validated initial observations for professor review",async()=>{const {d}=fixture(),key=`${d.snapshot.checkpoint.objectiveIds[0]}-reasoning`;let calls=0;const r=await engine.evaluateStudentEvidence(d,undefined,async(tier,system,input)=>{calls++;if(tier==="judge")throw new Error("judge unavailable");return modelOf({[key]:(t,i)=>observation(t,i,"AMBIGUOUS")})(tier,system,input);});assert.equal(calls,2);assert.equal(r.bundle.status,"needs_review");assert.ok(r.bundle.followupTargetIds.includes(key));assert.equal(r.events.find(e=>e.targetId===key).status,"AMBIGUOUS");assert.ok(r.evaluation);});
test("invented quotes and unrelated response IDs reject all positive model claims",async()=>{const {d}=fixture();for(const override of [(t,i)=>({...observation(t,i),supports:[{evidenceId:"work",start:0,end:10,quote:"not in work"}]}),(t,i)=>({...observation(t,i),supports:[{evidenceId:"somebody-else",start:0,end:4,quote:"fake"}]})]){const r=await engine.evaluateStudentEvidence(d,undefined,modelOf({[`${d.snapshot.checkpoint.objectiveIds[0]}-reasoning`]:override}));assert.equal(r.bundle.status,"unavailable");assert.equal(r.evaluation,null);assert.ok(r.events.every(e=>e.status==="AMBIGUOUS"));}});
test("provider outage is unavailable, not an incorrect-understanding judgment",async()=>{const {d}=fixture();const r=await engine.evaluateStudentEvidence(d,undefined,async()=>{throw new Error("provider timeout");});assert.equal(r.bundle.status,"unavailable");assert.equal(r.evaluation,null);assert.ok(r.events.every(e=>e.status==="AMBIGUOUS"));});
test("server-side code results are deterministic but never prove reasoning",async()=>{const {d}=fixture();d.data.evidence[0].modality="code";d.data.evidence[0].execution={source:"server",passed:3,failed:1,output:"3 passed; 1 failed"};d.data.evidence=d.data.evidence.filter(e=>e.kind!=="explanation");const r=await engine.evaluateStudentEvidence(d);const checks=r.events.filter(e=>e.type==="DIRECT_CORRECTNESS");assert.equal(checks.length,d.snapshot.checkpoint.objectiveIds.length);assert.ok(checks.every(e=>e.evaluator==="deterministic"&&e.status==="PARTIALLY_SUPPORTED"));assert.ok(r.events.filter(e=>e.type==="EXPLANATION").every(e=>e.status==="NOT_OBSERVED"));assert.equal(r.evaluation,null);});
test("legacy assessment yields rubric-based targets without an authentic design",async()=>{const {d}=fixture();delete d.snapshot.checkpoint.authentic;const targets=engine.evidenceTargets(d);assert.equal(targets.length,d.snapshot.checkpoint.objectiveIds.length*3);assert.ok(targets.every(t=>t.expected&&t.criterion));});
test.after(async()=>{await fs.rm(temp,{recursive:true,force:true});});
