"use client";
import { useState } from "react";
import { Download, RefreshCw, Users, Waves, Lightbulb } from "lucide-react";
import { Panel, Badge, Select, useWorkspace, exportJson } from "./course-ui";
import { useLearning } from "./learning-context";
import { learningConfig, studentMastery, emptyRecord, type LearningRecord, type Mastery } from "@/lib/novalearn/learning-domain";
import { masteryTone, SupportItem } from "./adaptive-student";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table";

export function ConceptInsights() {
  const w = useWorkspace(), l = useLearning(), config = learningConfig(w.course.data);
  const ids = [...new Set([...w.enrollments.filter(e => e.class_id === w.course.class_id).map(e => e.student_id), ...l.records.map(r => r.student_id), ...w.demonstrations.filter(d => d.course_id === w.course.id).map(d => d.student_id)])] as string[];
  const rows = ids.map(id => { const record = l.records.find(r => r.student_id === id) || emptyRecord(w.course.id, id, `empty-${id}`); return { id, record, states: studentMastery(w.course, record, w.demonstrations) }; });
  const name = (id: string) => w.profiles.find(p => p.id === id)?.name || "Enrolled student";
  const [selected, setSelected] = useState<{ id: string; conceptId: string } | null>(null), [targets, setTargets] = useState<string[]>([]), [kind, setKind] = useState("Practice"), [note, setNote] = useState(""), [conceptId, setConceptId] = useState("");
  const chosen = selected && rows.find(r => r.id === selected.id), state = chosen && chosen.states.find(s => s.conceptId === selected.conceptId);
  const attempts = rows.flatMap(r => r.record.data.attempts.filter((a, i, all) => all.findIndex(x => x.activityId === a.activityId) === i).map(a => ({ ...a, studentId: r.id })));
  const calibration = attempts.filter(a => !a.correct && a.confidence >= 4);
  const support = rows.flatMap(r => r.record.data.support.map(s => ({ ...s, studentId: r.id }))).sort((a,b) => Number(a.status === "Resolved") - Number(b.status === "Resolved") || a.at.localeCompare(b.at));
  return <Panel className="concept-insights"><div className="section-title"><div><p className="eyebrow">From lecture to understanding</p><h2>Learning observatory</h2><p>See the evidence early. Choose the right support.</p></div><div className="course-actions"><button className="secondary" aria-label="Refresh class learning evidence" onClick={() => w.run(l.refresh)}><RefreshCw size={16} /></button><button className="secondary" onClick={() => exportJson("novalearn-learning-evidence.json", { course: w.course.title, exportedAt: new Date().toISOString(), model: "weighted-bkt-1", records: l.records, mastery: rows.map(r => ({studentId:r.id,states:r.states})) })}><Download size={16} /> Export</button></div></div><div className="learning-summary"><div><Users size={20} /><strong>{rows.length}</strong><span>enrolled learners</span></div><div><Waves size={20} /><strong>{attempts.length}</strong><span>first-attempt checks</span></div><div><Lightbulb size={20} /><strong>{calibration.length}</strong><span>confidence mismatches</span></div><div><strong>{support.filter(s => s.status === "Open").length}</strong><span>open support actions</span></div></div>
    <Tabs defaultValue="mastery"><TabsList><TabsTrigger value="mastery">Concept mastery</TabsTrigger><TabsTrigger value="pulse">Live pulse</TabsTrigger><TabsTrigger value="support">Support desk</TabsTrigger></TabsList>
      <TabsContent value="mastery"><p className="fine">Select a cell to inspect its evidence. Updates are saved immediately; use Refresh to fetch new class activity. No-data cells are not failures. These model estimates are not grades.</p><div className="heatmap-legend"><span className="strong">Strong</span><span className="developing">Developing</span><span className="practice">Needs practice</span><span className="unknown">Insufficient evidence</span></div><div className="heatmap-scroll"><Table><TableHeader><TableRow><TableHead>Student</TableHead>{config.concepts.map(c => <TableHead key={c.id}>{c.name}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r => <TableRow key={r.id}><TableCell>{name(r.id)}</TableCell>{r.states.map(m => <TableCell key={m.conceptId}><button className={`heat-cell ${masteryTone(m)}`} title={`${name(r.id)} · ${m.label} · ${m.count} evidence events`} onClick={() => setSelected({id:r.id,conceptId:m.conceptId})}><b>{m.count ? `${Math.round(m.probability * 100)}%` : "—"}</b><small>{m.label}</small></button></TableCell>)}</TableRow>)}</TableBody></Table></div>{!rows.length && <p>Invite students to the linked class to start your concept map.</p>}{chosen && state && <EvidenceDetail student={name(chosen.id)} state={state} record={chosen.record} />}
        <h3>Where a small intervention could help</h3><div className="hotspot-grid">{config.concepts.map(c => { const states = rows.map(r => r.states.find(s => s.conceptId === c.id)!); const need = states.filter(s => s.label === "Needs practice").length, missing = states.filter(s => s.label === "Insufficient evidence").length; return <div className="hotspot" key={c.id}><b>{c.name}</b><p>{need} need practice · {missing} need more evidence</p><button className="link" onClick={() => { setConceptId(c.id); setTargets(rows.filter(r => r.states.find(s => s.conceptId === c.id)?.label === "Needs practice").map(r => r.id)); setNote(`Review a worked example of ${c.name}, then explain it in your own words and try a different scenario.`); }}>Prepare targeted support</button></div>; })}</div>
      </TabsContent>
      <TabsContent value="pulse"><h3>Checks before the checkpoint</h3><p>Correctness and self-reported confidence are separate signals. Explanations require review; a wrong answer is not an automatic misconception diagnosis.</p>{config.activities.map(a => { const responses = attempts.filter(p => p.activityId === a.id), correct = responses.filter(p => p.correct).length; return <details className="pulse-row" key={a.id}><summary><span><Badge>{a.kind}</Badge><b>{a.title}</b></span><span>{responses.length} responses · {responses.length ? Math.round(correct / responses.length * 100) : "—"}% correct</span></summary><p>{a.question}</p>{a.options.map((o, i) => { const n = responses.filter(p => p.selected === i).length; return <div className="pulse-option" key={i}><span>{o}</span><meter value={n} min={0} max={Math.max(1,responses.length)} /><b>{n}</b></div>; })}{responses.map(p => <article className="pulse-response" key={p.id}><b>{name(p.studentId)} · confidence {p.confidence}/5</b><p>{p.explanation}</p>{p.reflection && <blockquote>{p.reflection}</blockquote>}<QuickReview record={rows.find(r => r.id === p.studentId)!.record} attemptId={p.id} /></article>)}</details>; })}<div className="course-actions"><button className="primary" onClick={() => w.navigate("modules")}>Create a pulse check</button></div></TabsContent>
      <TabsContent value="support"><h3>Prioritized support queue</h3><p className="fine">Open requests are shown oldest first. High confidence with an incorrect response is a discussion prompt—not a label about a student.</p>{calibration.length > 0 && <div className="course-notice">{calibration.length} responses suggest a confidence mismatch. Inspect them in Live pulse before intervening.</div>}<div className="tags">{config.concepts.map(c => { const count = support.filter(s => s.conceptId === c.id && s.status === "Open").length; return count ? <span key={c.id}>{c.name}: {count} open requests</span> : null; })}</div>{support.map(s => <div key={s.id}><h4>{name(s.studentId)}</h4><SupportItem item={s} studentId={s.studentId} /></div>)}{!support.length && <p>No support requests yet. Students can ask questions or request office hours from My progress.</p>}</TabsContent>
    </Tabs>
    <details className="intervention-composer" open={targets.length > 0 || undefined}><summary>Assign targeted support · professor decides</summary><form onSubmit={e => { e.preventDefault(); w.run(async () => { const completed: string[] = []; try { for (const studentId of targets) { await l.act("intervene", {studentId,kind,conceptId,note}); completed.push(studentId); } } finally { setTargets(old => old.filter(id => !completed.includes(id))); if (completed.length) w.notice(`Support assigned to ${completed.length} student(s).`); } }); }}><div className="course-form-grid"><Select label="Support type" value={kind} onChange={setKind} options={["Practice","Reteach","Office hours"].map(v=>({value:v,label:v}))}/><Select label="Concept" value={conceptId} onChange={setConceptId} options={[{value:"",label:"General course support"},...config.concepts.map(c=>({value:c.id,label:c.name}))]}/></div><div className="concept-prereqs">{rows.map(r=><label key={r.id}><input type="checkbox" checked={targets.includes(r.id)} onChange={e=>setTargets(e.target.checked?[...targets,r.id]:targets.filter(id=>id!==r.id))}/>{name(r.id)}</label>)}</div><label>Specific next step<textarea required minLength={3} maxLength={3000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={!targets.length || w.busy || l.loading}>Assign to {targets.length} student(s)</button><p className="fine">Students see this in their support plan. Office-hour actions are requests; no external calendar invitations are sent.</p></form></details>
  </Panel>;
}
function EvidenceDetail({student,state,record}:{student:string;state:Mastery;record:LearningRecord}) {
  const w=useWorkspace(),c=learningConfig(w.course.data).concepts.find(c=>c.id===state.conceptId);
  return <section className="evidence-detail"><h3>{student} · {c?.name}</h3><Badge>{state.label}</Badge><p>{state.uncertainty}</p>{state.history.map(h=><article className="evidence-event" key={h.signal.id}><b>{h.signal.modality} · {new Date(h.at).toLocaleString()}</b><p>{h.signal.rationale}</p><small>{Math.round(h.before*100)}% → {Math.round(h.after*100)}% · weight {h.signal.strength}</small></article>)}{record.data.attempts.filter(a=>a.conceptIds.includes(state.conceptId)).map(a=><details key={a.id}><summary>{a.activityTitle} · confidence {a.confidence}/5</summary><p>Selected: {a.answerText}</p><p>{a.explanation}</p>{a.reflection&&<blockquote>{a.reflection}</blockquote>}<QuickReview record={record} attemptId={a.id}/></details>)}{!state.history.length&&<p>No usable evidence yet. Start with a low-stakes diagnostic.</p>}</section>;
}
function QuickReview({record,attemptId}:{record:LearningRecord;attemptId:string}) {
  const w=useWorkspace(),l=useLearning(),[rationale,setRationale]=useState(""),[demonstrated,setDemonstrated]=useState("yes");
  const a=record.data.attempts.find(a=>a.id===attemptId)!;
  if(record.data.attempts.find(x=>x.activityId===a.activityId)?.id!==attemptId)return <p className="fine">Repeat practice; no additional mastery evidence.</p>;
  return <details><summary>Review explanation evidence</summary><form onSubmit={e=>{e.preventDefault();w.run(async()=>{await l.act("review",{studentId:record.student_id,attemptId,demonstrated:demonstrated==="yes",rationale});setRationale("");w.notice("Professor judgment saved. It replaces, rather than duplicates, this check’s automatic signal.");});}}><Select label="Does this response demonstrate the concept?" value={demonstrated} onChange={setDemonstrated} options={[{value:"yes",label:"Yes · reasoning supports understanding"},{value:"no",label:"Not yet · further practice needed"}]}/><label>Evidence-based rationale<textarea required minLength={3} maxLength={3000} rows={2} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button className="secondary">Save professor judgment</button></form></details>;
}
