"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Compass, LockKeyhole, MessageCircle, RefreshCw, Target } from "lucide-react";
import { Panel, Badge, Select, useWorkspace } from "./course-ui";
import { useLearning } from "./learning-context";
import { learningConfig, isReleased, recommend, studentMastery, type Activity, type Mastery, type Support } from "@/lib/novalearn/learning-domain";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
export const masteryTone = (m: Mastery) => m.label === "Strong" ? "strong" : m.label === "Developing" ? "developing" : m.label === "Needs practice" ? "practice" : "unknown";

export function AdaptivePath() {
  const w = useWorkspace(), l = useLearning(), config = learningConfig(w.course.data), record = l.records.find(r => r.student_id === w.profile.id), states = studentMastery(w.course, record, w.demonstrations, w.profile.id), next = recommend(w.course, states);
  const [selected, setSelected] = useState("");
  useEffect(() => setSelected(""), [w.course.id]);
  function startNext() {
    if (!next) return;
    w.setModuleId(next.concept.moduleId);
    const fresh = config.activities.find(a => a.approved && a.conceptIds.includes(next.concept.id) && !record?.data.attempts.some(p => p.activityId === a.id));
    setSelected(fresh?.id || "");
    if (!fresh) w.notice("No new quick check is available for this concept. Review the materials, explain it to Nova, or ask your professor for another applied task. Repeating a revealed answer does not add mastery evidence.");
  }
  const activities = config.activities.filter(a => a.approved && a.moduleId === w.moduleId && isReleased(w.course.data, a.moduleId));
  const a = activities.find(a => a.id === selected);
  return <>
    <Panel className="adaptive-hero"><div><p className="eyebrow">One destination. Your own path.</p><h2><Compass size={24} /> Your next best step</h2><h3>{next?.concept.name || "Your course is taking shape"}</h3><p>{next?.reason || "Your professor will release your first module soon."}</p><div className="course-actions">{next && <><Badge>{next.track} track</Badge><Badge>{next.mode}</Badge><button className="primary" onClick={startNext}>Start this step <ArrowRight size={16} /></button></>}</div><p className="fine">Recommendations use evidence, prerequisites, and review dates—not fixed “learning styles.” Your course objectives stay the same.</p></div><div className="adaptive-orbit"><Target size={54} /><span>{states.filter(s => s.label === "Strong").length}<small>concepts with strong evidence</small></span></div></Panel>
    <div className="learning-roadmap" aria-label="Course roadmap">{w.course.data.modules.map((m, i) => <button className={w.moduleId === m.id ? "selected" : ""} key={m.id} onClick={() => w.setModuleId(m.id)}><span className="roadmap-number">{isReleased(w.course.data, m.id) ? i + 1 : <LockKeyhole size={16} />}</span><span><small>Week {m.week} · {isReleased(w.course.data, m.id) ? "Open" : "Not released"}</small><b>{m.title}</b></span></button>)}</div>
    <Panel><div className="section-title"><div><h2>Check in with your understanding</h2><p>Choose, explain, and tell us how confident you feel. No grades attached.</p></div><Badge>Low stakes</Badge></div><div className="quick-check-grid">{activities.map(a => <button className={selected === a.id ? "quick-card selected" : "quick-card"} key={a.id} onClick={() => setSelected(a.id)}><Badge>{a.kind}</Badge><h3>{a.title}</h3><span>{a.difficulty} · 3–5 min</span>{record?.data.attempts.some(p => p.activityId === a.id) && <small><CheckCircle2 size={14} /> Practiced · repeat without extra mastery credit</small>}</button>)}</div>{!activities.length && <p className="fine">{isReleased(w.course.data, w.moduleId) ? "No quick checks released in this module yet. Explore the teaching materials below." : "This module is on your roadmap. Its materials, checks, and tutor will open when your professor releases it."}</p>}{a && <QuickAttempt key={`${w.course.id}-${a.id}`} activity={a} />}</Panel>
  </>;
}
function QuickAttempt({ activity: a }: { activity: Activity }) {
  const w = useWorkspace(), l = useLearning(), record = l.records.find(r => r.student_id === w.profile.id);
  const [selected, setSelected] = useState(-1), [explanation, setExplanation] = useState(""), [confidence, setConfidence] = useState("3"), [hints, setHints] = useState(false), [reflection, setReflection] = useState(""), [started] = useState(Date.now());
  const last = record?.data.attempts.filter(p => p.activityId === a.id).at(-1);
  return <form className="quick-attempt" onSubmit={e => { e.preventDefault(); w.run(async () => { await l.act("attempt", { activityId: a.id, publicationVersion: w.course.version, selected, explanation, confidence: +confidence, hints, reflection, elapsedSeconds: Math.min(7200, Math.floor((Date.now() - started) / 1000)) }); w.notice("Your check and explanation are saved. Your learning path has updated."); }); }}><h3>{a.question}</h3><fieldset className="answer-options"><legend className="sr-only">Choose one answer</legend>{a.options.map((o, i) => <label key={i} className={selected === i ? "selected" : ""}><input type="radio" name={`answer-${a.id}`} value={i} checked={selected === i} onChange={() => setSelected(i)} required /><span>{o}</span></label>)}</fieldset><label>Why did you choose it?<textarea rows={3} minLength={10} maxLength={3000} required value={explanation} onChange={e => setExplanation(e.target.value)} placeholder="Explain the principle and connect it to this scenario…" /></label><div className="course-form-grid"><Select label="Your confidence · not a score" value={confidence} onChange={setConfidence} options={["1 · Guessing", "2 · Unsure", "3 · Somewhat sure", "4 · Confident", "5 · Very confident"].map((label, i) => ({ label, value: String(i + 1) }))} /><label className="check"><input type="checkbox" checked={hints} onChange={e => setHints(e.target.checked)} /> I used notes, hints, or other help</label></div><label>Reflection · optional<textarea rows={2} value={reflection} maxLength={2000} onChange={e => setReflection(e.target.value)} placeholder="What still feels uncertain? What would change your answer?" /></label><button className="primary" type="submit" disabled={w.busy || l.loading || !!l.error || selected < 0 || explanation.trim().length < 10}>Save my check <ArrowRight size={16} /></button>{last && <div className={`check-feedback ${last.correct ? "correct" : "retry"}`} role="status"><b>{last.correct ? "Good connection." : "A useful place to learn."}</b><p>{last.feedback}</p><small>Saved {new Date(last.at).toLocaleString()} · confidence {last.confidence}/5 · your explanation is available to your professor.</small></div>}</form>;
}
export function MasteryProgress() {
  const w = useWorkspace(), l = useLearning(), record = l.records.find(r => r.student_id === w.profile.id), concepts = learningConfig(w.course.data).concepts, states = studentMastery(w.course, record, w.demonstrations, w.profile.id);
  const [goal, setGoal] = useState(record?.data.goal || "");
  useEffect(() => setGoal(record?.data.goal || ""), [record?.data.goal]);
  return <><Panel><div className="section-title"><div><p className="eyebrow">Understanding, not just a grade</p><h2>Your concept mastery</h2></div><button className="secondary" onClick={() => w.run(l.refresh)} aria-label="Refresh learning evidence"><RefreshCw size={16} /></button></div><p className="fine">These are uncalibrated learning estimates from observed evidence. “Insufficient evidence” means we need more information, not that you lack ability. AI suggestions do not directly change mastery.</p><div className="mastery-cards">{states.map(m => <details key={m.conceptId} className={`mastery-card ${masteryTone(m)}`}><summary><span>{concepts.find(c => c.id === m.conceptId)?.name}</span><Badge>{m.label}</Badge><small>{m.count} evidence {m.count === 1 ? "event" : "events"}</small></summary><p>{m.uncertainty}</p>{m.count > 0 && <p>Model estimate: {Math.round(m.probability * 100)}% · next review {m.dueAt ? new Date(m.dueAt).toLocaleDateString() : "after your first check"}</p>}{m.history.map(h => <div className="evidence-event" key={h.signal.id}><b>{h.signal.modality} · {new Date(h.at).toLocaleDateString()}</b><p>{h.signal.rationale}</p><small>{Math.round(h.before * 100)}% → {Math.round(h.after * 100)}% · evidence weight {h.signal.strength}</small></div>)}{!m.count && <p>Try a diagnostic or an applied checkpoint. Missing evidence is never counted as an incorrect answer.</p>}</details>)}</div></Panel><Panel><h3>Your learning goal</h3><form onSubmit={e => { e.preventDefault(); w.run(async () => { await l.act("goal", { goal }); w.notice("Learning goal saved."); }); }}><label>What would you like to be able to do?<textarea required minLength={3} maxLength={3000} value={goal} onChange={e => setGoal(e.target.value)} rows={2} placeholder="I want to explain my design decisions confidently…" /></label><button className="secondary" disabled={w.busy || l.loading}>Save goal</button></form></Panel><StudentSupport /></>;
}
export function StudentSupport() {
  const w = useWorkspace(), l = useLearning(), record = l.records.find(r => r.student_id === w.profile.id), concepts = learningConfig(w.course.data).concepts;
  const [kind, setKind] = useState("Question"), [conceptId, setConceptId] = useState(""), [note, setNote] = useState("");
  return <Panel><h2><MessageCircle size={22} /> Your support space</h2><p>Ask a question, request office hours, or follow up on your professor’s suggested next step.</p><Tabs defaultValue="inbox"><TabsList><TabsTrigger value="inbox">Your support plan</TabsTrigger><TabsTrigger value="request">Ask for help</TabsTrigger></TabsList><TabsContent value="inbox">{record?.data.support.length ? record.data.support.slice().reverse().map(s => <SupportItem key={s.id} item={s} studentId={w.profile.id} />) : <p>No support requests yet. You can ask at any time.</p>}</TabsContent><TabsContent value="request"><form onSubmit={e => { e.preventDefault(); w.run(async () => { await l.act("support", { kind, conceptId, note }); setNote(""); w.notice("Request saved to your professor’s support queue."); }); }}><div className="course-form-grid"><Select label="How can we help?" value={kind} onChange={setKind} options={["Question", "Office hours", "Practice", "Reteach"].map(v => ({ value: v, label: v }))} /><Select label="Concept · optional" value={conceptId} onChange={setConceptId} options={[{ value: "", label: "General course question" }, ...concepts.map(c => ({ value: c.id, label: c.name }))]} /></div><label>What have you tried, and where are you stuck?<textarea rows={3} minLength={3} maxLength={3000} required value={note} onChange={e => setNote(e.target.value)} /></label><button className="primary" disabled={l.loading || w.busy || !!l.error}>Send support request</button><p className="fine">This is an in-app request, not a calendar booking or an emergency service.</p></form></TabsContent></Tabs></Panel>;
}
export function SupportItem({ item: s, studentId }: { item: Support; studentId: string }) {
  const w = useWorkspace(), l = useLearning(), teacher = w.profile.role === "teacher", [reply, setReply] = useState(s.reply), [status, setStatus] = useState<string>(s.status);
  return <article className="support-item"><div className="section-title"><Badge tone={s.status === "Resolved" ? "green" : "amber"}>{s.kind} · {s.status}</Badge><small>{new Date(s.at).toLocaleDateString()}</small></div><b>{s.by === "teacher" ? "Professor’s next step" : "Student request"}</b><p>{s.note}</p>{s.reply && <blockquote>{s.reply}</blockquote>}{(teacher || (s.by === "teacher" && s.status === "Open")) && <form onSubmit={e => { e.preventDefault(); w.run(async () => { await l.act("respond", { studentId, supportId: s.id, reply, status }); w.notice("Support update saved."); }); }}><label>{teacher ? "Your response" : "What changed after this activity?"}<textarea required minLength={3} maxLength={3000} rows={2} value={reply} onChange={e => setReply(e.target.value)} /></label>{teacher && <Select label="Request status" value={status} onChange={setStatus} options={[{value:"Open",label:"Keep open"},{value:"Resolved",label:"Resolved"}]} />}<button className="secondary">{teacher ? "Save response" : "Complete and reflect"}</button></form>}</article>;
}
