"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2, Sparkles, Save, RotateCcw, ShieldCheck, Download } from "lucide-react";
import { useWorkspace, Panel, Nova, Badge, Select, Empty, exportJson, SourceLinks } from "./course-ui";
import { AssessmentStudio } from "./course-architect";
import { Tabs, TabsList, TabsTrigger } from "./ui/tabs";
import { assessmentStages, nextAssessmentStage, assessmentIssues, assessmentFingerprint, assessmentCheckpoint } from "@/lib/novalearn/assessment-engine";
import type { AssessmentDesign, AssessmentInput } from "@/lib/novalearn/course-domain";

const choices=(values:string[])=>values.map(value=>({value,label:value}));
export function AuthenticAssessmentStudio(){
  const w=useWorkspace();
  const [view,setView]=useState("design"),[selected,setSelected]=useState(""),[stage,setStage]=useState(0);
  const [draft,setDraft]=useState<AssessmentInput>({moduleId:w.moduleId,objectiveIds:w.course.data.modules.find(m=>m.id===w.moduleId)?.objectiveIds.slice(0,8)||[],category:"Assignment",format:"Case study",emphasis:"Apply concepts, explain decisions, and transfer to a new scenario.",duration:60,difficulty:"Core",verification:"Standard",aiPolicy:"Planning only; disclose use",collaboration:"Individual",resources:"Approved course materials; declare any other assistance.",knowledgeQuestions:0});
  const data=w.course.data,design=data.assessmentDesigns?.find(d=>d.id===selected),input=design?.inputs||draft;
  const update=(patch:Partial<AssessmentDesign>)=>{if(design)w.change({assessmentDesigns:data.assessmentDesigns!.map(d=>d.id===design.id?{...d,...patch,approvedFingerprint:undefined,validatedFingerprint:undefined}:d)});};
  const setInput=(patch:Partial<AssessmentInput>)=>design?update({inputs:{...input,...patch}}):setDraft({...input,...patch});
  const objectives=input.category==="Final project"?data.objectives:data.objectives.filter(o=>data.modules.find(m=>m.id===input.moduleId)?.objectiveIds.includes(o.id));
  const issues=design?assessmentIssues(data,design):[],next=design?nextAssessmentStage(design):undefined;
  const validated=!!design&&design.validatedFingerprint===assessmentFingerprint(design)&&!issues.length;
  const approved=validated&&design?.approvedFingerprint===assessmentFingerprint(design);
  async function action(name:string,body:any={}){
    await w.run(async()=>{try{const saved=await w.save();if(name==="assessment-step"){const savedDesign=saved.data.assessmentDesigns?.find(d=>d.id===design?.id);body={...body,key:savedDesign?nextAssessmentStage(savedDesign)?.key:body.key};}const row=await w.call(name,{courseId:saved.id,version:saved.version,designId:design?.id,...body});w.setCourse(row);if(name==="assessment-create"){setSelected(row.data.assessmentDesigns.at(-1).id);setStage(0);}if(name==="assessment-step"){const d=row.data.assessmentDesigns.find((d:AssessmentDesign)=>d.id===selected);const pending=nextAssessmentStage(d);setStage(pending?assessmentStages.findIndex(s=>s.key===pending.key):5);}w.notice(name==="assessment-approve"?"Assessment approved for the next release. Student publication is a separate action.":"Assessment progress saved.");}finally{await w.reload();}});
  }
  if(!data.graphApproved)return <Empty title="Begin with approved learning objectives" text="The Authentic Assessment Engine uses your existing course graph. Approve it in Course Compiler, then return here." action={()=>w.navigate("architect")} label="Review course graph"/>;
  return <>
    <div className="assessment-heading"><div><p className="eyebrow">ENGINE 02 · PROFESSOR LED</p><h1>Authentic Assessment Studio</h1><p>Turn learning objectives into evidence of real understanding.</p></div><Badge tone={w.preview?"amber":"green"}>{w.preview?"Preview templates · no live AI":"Connected model gateway"}</Badge></div>
    <Tabs className="assessment-tabs" value={view} onValueChange={setView}><TabsList><TabsTrigger value="design">Design engine</TabsTrigger><TabsTrigger value="library">Existing assessments</TabsTrigger></TabsList></Tabs>
    {view==="library"?<AssessmentStudio/>:<div className="main-grid assessment-engine"><div>
      <Panel><div className="section-title"><h2>Your assessment designs</h2><button className="secondary" onClick={()=>{setSelected("");setStage(0);}}>New design</button></div><Select label="Saved design" value={selected} onChange={id=>{setSelected(id);setStage(0);}} options={[{value:"",label:"Create a new assessment"},...(data.assessmentDesigns||[]).map(d=>({value:d.id,label:`${d.task?.title||d.inputs.category+" · "+data.modules.find(m=>m.id===d.inputs.moduleId)?.title}${d.approvedFingerprint?" · approved":" · draft"}`}))]}/></Panel>
      <Panel><details open={!design}><summary><h2 className="inline-title">1. Professor intent & constraints</h2></summary><div className="course-form-grid">
        <Select label="Module" value={input.moduleId} onChange={moduleId=>setInput({moduleId,objectiveIds:data.modules.find(m=>m.id===moduleId)?.objectiveIds.slice(0,8)||[]})} options={data.modules.map(m=>({value:m.id,label:m.title}))}/>
        <Select label="Assessment category" value={input.category} onChange={category=>setInput({category:category as any,objectiveIds:data.modules.find(m=>m.id===input.moduleId)?.objectiveIds.slice(0,8)||[]})} options={choices(["Assignment","Checkpoint","Final project","Teach Nova"])}/>
        <Select label="Real-world format" value={input.format} onChange={format=>setInput({format:format as any})} options={choices(["Case study","Design challenge","Data investigation","Teach Nova","Applied problem"])}/>
        <Select label="Difficulty" value={input.difficulty} onChange={difficulty=>setInput({difficulty:difficulty as any})} options={choices(["Foundation","Core","Challenge"])}/>
        <label>Total time budget · minutes<input type="number" min={15} max={600} value={input.duration} onChange={e=>setInput({duration:Number(e.target.value)})}/></label>
        <label>Maximum recall-only questions · 0–5<input type="number" min={0} max={5} value={input.knowledgeQuestions} onChange={e=>setInput({knowledgeQuestions:Number(e.target.value)})}/></label>
        <Select label="Verification depth" value={input.verification} onChange={verification=>setInput({verification:verification as any})} options={choices(["Standard","Extended"])}/>
        <Select label="Collaboration" value={input.collaboration} onChange={collaboration=>setInput({collaboration:collaboration as any})} options={choices(["Individual","Group artifact; individual defense"])}/>
      </div><Select label="AI assistance policy" value={input.aiPolicy} onChange={aiPolicy=>setInput({aiPolicy:aiPolicy as any})} options={choices(["No AI assistance","Planning only; disclose use","AI allowed; disclose and verify"])}/><label>What should students demonstrate?<textarea rows={3} maxLength={1500} value={input.emphasis} onChange={e=>setInput({emphasis:e.target.value})}/></label><label>Permitted resources & constraints<textarea rows={2} maxLength={2000} value={input.resources} onChange={e=>setInput({resources:e.target.value})}/></label>
      <fieldset><legend>Assessed objectives · choose up to 8</legend>{objectives.map(o=><label className="course-check" key={o.id}><input type="checkbox" checked={input.objectiveIds.includes(o.id)} onChange={e=>setInput({objectiveIds:e.target.checked?[...input.objectiveIds,o.id]:input.objectiveIds.filter(id=>id!==o.id)})}/>{o.title} <Badge>{o.level}</Badge></label>)}</fieldset>
      <p className="fine">Standard: artifact, explanation, two follow-ups and transfer. Extended also requires reflection. Group work still produces an individual evidence bundle. Policy is disclosed, not surveillance-enforced.</p>
      {!design?<button className="primary" disabled={!input.objectiveIds.length||w.busy} onClick={()=>action("assessment-create",{inputs:input})}><Sparkles size={16}/> Create design workspace</button>:<p className="fine">Changing these inputs resets this design’s dependent outputs when saved. Other assessments and Course Compiler content remain unchanged.</p>}</details></Panel>
      {design&&<>
        <div className="assessment-pipeline">{assessmentStages.map((s,i)=>{const log=design.log.find(l=>l.key===s.key);return <button key={s.key} onClick={()=>setStage(i)} className={stage===i?"active":""}><span>{log?.status==="complete"?<CheckCircle2 size={18}/>:i+1}</span><strong>{s.title}</strong><small>{log?.status||"Pending"}</small></button>;})}</div>
        <Panel><div className="section-title"><div><p className="eyebrow">STRUCTURED STAGE {stage+1} OF 6</p><h2>{assessmentStages[Math.max(0,stage)].title}</h2></div><button className="link" onClick={()=>{if(window.confirm("Regenerate this stage and its dependent outputs? Saved student submissions and the current publication will not change."))action("assessment-reset",{key:assessmentStages[Math.max(0,stage)].key});}}><RotateCcw size={14}/> Regenerate from here</button></div>
        {stage===0&&(design.evidence?<>{design.evidence.map((e,i)=><div className="assessment-evidence" key={e.objectiveId}><h3>{data.objectives.find(o=>o.id===e.objectiveId)?.title}</h3>{(["observable","artifact","reasoning","transfer"] as const).map(key=><label key={key}>{key}<textarea rows={2} value={e[key]} maxLength={1000} onChange={event=>update({evidence:design.evidence!.map((row,j)=>j===i?{...row,[key]:event.target.value}:row)})}/></label>)}</div>)}</>:<p>Nova will map each objective to observable work, reasoning and transfer evidence.</p>)}
        {stage===1&&(design.strategy?<><label>Strategy rationale<textarea rows={3} value={design.strategy.rationale} onChange={e=>update({strategy:{...design.strategy!,rationale:e.target.value}})}/></label><ol>{design.strategy.sequence.map((s,i)=><li key={i}>{s}</li>)}</ol><label>Accessibility & equivalent alternatives<textarea rows={3} value={design.strategy.accessibility} onChange={e=>update({strategy:{...design.strategy!,accessibility:e.target.value}})}/></label></>:<p>Choose a sequence that elicits the evidence, with accessible response options and individual accountability.</p>)}
        {stage===2&&(design.task?<><label>Assessment title<input value={design.task.title} maxLength={200} onChange={e=>update({task:{...design.task!,title:e.target.value}})}/></label><label>Scenario<textarea rows={5} value={design.task.scenario} maxLength={4000} onChange={e=>update({task:{...design.task!,scenario:e.target.value}})}/></label><label>Instructions & deliverables<textarea rows={4} value={design.task.instructions} maxLength={5000} onChange={e=>update({task:{...design.task!,instructions:e.target.value}})}/></label>{design.task.tasks.map((t,i)=><div className="assessment-evidence" key={t.id}><div className="section-title"><Badge>{t.kind}</Badge><span>{t.objectiveIds.join(" · ")}</span></div><label>Task prompt<textarea rows={3} value={t.prompt} maxLength={1800} onChange={e=>update({task:{...design.task!,tasks:design.task!.tasks.map((row,j)=>i===j?{...row,prompt:e.target.value}:row)}})}/></label><label>Estimated minutes<input type="number" min={1} max={600} value={t.minutes} onChange={e=>update({task:{...design.task!,tasks:design.task!.tasks.map((row,j)=>i===j?{...row,minutes:Number(e.target.value)}:row)}})}/></label></div>)}<SourceLinks ids={design.task.sourceIds}/>{!design.task.sourceIds.length&&<p className="course-warning">No approved source citations. This is an ungrounded draft; independently verify every subject-specific claim.</p>}</>:<p>Generate a self-contained application scenario, explicit deliverables and an objective-linked task sequence.</p>)}
        {stage===3&&(design.scoring?<>{design.scoring.rubric.map((r,i)=><div className="assessment-evidence" key={r.objectiveId}><h3>{r.criterion}</h3><label>Criterion<input value={r.criterion} onChange={e=>update({scoring:{...design.scoring!,rubric:design.scoring!.rubric.map((row,j)=>i===j?{...row,criterion:e.target.value}:row)}})}/></label><label>Weight %<input type="number" min={1} max={100} value={r.weight} onChange={e=>update({scoring:{...design.scoring!,rubric:design.scoring!.rubric.map((row,j)=>i===j?{...row,weight:Number(e.target.value)}:row)}})}/></label><label>Evidence descriptor<textarea value={r.descriptor} onChange={e=>update({scoring:{...design.scoring!,rubric:design.scoring!.rubric.map((row,j)=>i===j?{...row,descriptor:e.target.value}:row)}})}/></label>{design.scoring!.levels.filter(l=>l.objectiveId===r.objectiveId).map(l=><div key={l.objectiveId}>{(["excellent","proficient","developing","beginning"] as const).map(key=><label key={key}>{key}<textarea rows={2} value={l[key]} onChange={e=>update({scoring:{...design.scoring!,levels:design.scoring!.levels.map(row=>row.objectiveId===l.objectiveId?{...row,[key]:e.target.value}:row)}})}/></label>)}</div>)}</div>)}<strong>Total: {design.scoring.rubric.reduce((n,r)=>n+r.weight,0)} / 100%</strong></>:<p>Build transparent objective-linked criteria with four observable performance levels.</p>)}
        {stage===4&&(design.verification?<><label>Adaptive follow-up strategy<textarea rows={3} value={design.verification.followupStrategy} onChange={e=>update({verification:{...design.verification!,followupStrategy:e.target.value}})}/></label><label>Changed-scenario transfer<textarea rows={3} value={design.verification.transferPrompt} onChange={e=>update({verification:{...design.verification!,transferPrompt:e.target.value}})}/></label><h3>Equivalent student variants</h3><p className="fine">A stable variant is assigned when each student begins. Review equivalence before approval; this is not an authorship detector.</p>{design.verification.variants.map((v,i)=><label key={v.id}>{v.label}<textarea rows={2} value={v.change} onChange={e=>update({verification:{...design.verification!,variants:design.verification!.variants.map((row,j)=>i===j?{...row,change:e.target.value}:row)}})}/></label>)}<details><summary>Professor-private evaluation guide · never in student publication</summary>{design.verification.privateGuide.map((g,i)=><div className="assessment-evidence" key={g.objectiveId}><h3>{data.objectives.find(o=>o.id===g.objectiveId)?.title}</h3>{(["expectedReasoning","misconceptions","sufficientEvidence"] as const).map(key=><label key={key}>{key}<textarea rows={3} value={g[key]} onChange={e=>update({verification:{...design.verification!,privateGuide:design.verification!.privateGuide.map((row,j)=>i===j?{...row,[key]:e.target.value}:row)}})}/></label>)}</div>)}</details></>:<p>Create equivalent variants, adaptive probes, transfer prompts and a private guide for evidence review.</p>)}
        {stage===5&&<><h3>Alignment & workload review</h3><p>{design.alignment?.summary||"Validate the completed package, then review it as the professor."}</p><div className="assessment-metrics"><span><strong>{input.objectiveIds.length}</strong> objectives</span><span><strong>{design.task?.tasks.reduce((n,t)=>n+t.minutes,0)||0}/{input.duration}</strong> minutes</span><span><strong>{design.scoring?.rubric.reduce((n,r)=>n+r.weight,0)||0}%</strong> rubric total</span></div>{issues.length?<ul className="course-warning">{issues.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="success">Structural checks pass. Professor review is still required.</p>}{w.preview&&<p className="course-warning">Preview output is a template, not a subject-validated assessment. Edit the scenario before classroom use.</p>}<button className="primary" disabled={!validated||w.busy||approved} onClick={()=>action("assessment-approve")}><ShieldCheck size={16}/>{approved?"Professor approved":"I reviewed the package · approve"}</button><p className="fine">By approving, you confirm subject accuracy, difficulty, variant equivalence, permitted resources and fair rubric criteria. This does not publish automatically.</p></>}
        <div className="course-actions"><button className="secondary" onClick={()=>w.run(async()=>{await w.save();w.notice("Design edits saved; dependent stages may need regeneration.");})}><Save size={16}/> Save edits</button>{next&&<button className="primary" onClick={()=>action("assessment-step",{key:next.key})}><Sparkles size={16}/> Run {next.title}<ArrowRight size={16}/></button>}</div>
        </Panel>
        <Panel><div className="section-title"><h2>Review → approve → release</h2><Badge tone={approved?"green":"amber"}>{approved?"Approved for next release":"Professor review pending"}</Badge></div><p>Existing attempts keep their frozen assessment and rubric. New drafts never overwrite submitted work.</p><div className="course-actions"><button className="secondary" disabled={!design.verification||!design.scoring} onClick={()=>exportJson("NovaLearn-student-assessment.json",assessmentCheckpoint(design))}><Download size={16}/> Student package</button><button className="secondary" onClick={()=>exportJson("NovaLearn-professor-assessment-private.json",design)}><Download size={16}/> Private design JSON</button><button className="primary" disabled={!approved||w.busy} onClick={()=>w.run(async()=>{const saved=await w.save();await w.call("release",{courseId:saved.id});w.notice("Approved assessment released according to your course’s module-release settings.");})}>Release approved content</button></div><p className="fine">Course Compiler’s final review and module-release controls still apply. Private exports contain evaluation guidance; do not distribute them to students.</p></Panel>
        <details className="assessment-log"><summary>Generation history & model routes</summary>{design.log.map(l=><p key={l.key}><strong>{l.key} · {l.status}</strong> — {l.routing} · {(l.ms/1000).toFixed(1)}s<br/>{l.detail}</p>)}</details>
      </>}
    </div><aside><Nova text={!design?"Choose the learning objectives and the kind of evidence you want. Set a realistic time budget, resources and AI policy, then create a design workspace.":stage===5?"Review every finding, the workload and rubric. You make the final decision. Approve this package, then release it when your course is ready. I never assign a final grade or a cheating score.":`In ${assessmentStages[Math.max(0,stage)].title}, review and edit the output before continuing. Save your edits; dependent stages will be refreshed. Use Regenerate from here to revise only this assessment.`}/><Panel className="tinted"><h3>Evidence, not guesswork</h3><p>Applied artifact → explanation → adaptive follow-ups → changed-scenario transfer → professor review.</p><p className="fine">Six bounded stages, saved independently. Closing this page does not run a background job. Resume from the next pending stage.</p></Panel><Panel><h3>Protecting your current course</h3><p className="fine">Course Compiler, learning materials, mastery calculations and existing assessments remain in place. New assessment designs live alongside them.</p></Panel></aside></div>}
  </>;
}
