"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowRight, Check, Play, Pause, Download, Sparkles, ShieldCheck, Clock, BookOpen } from "lucide-react";
import { useWorkspace, Panel, Nova, Badge, Select, exportJson, readDocument, uid } from "./course-ui";
import { Architect, ModuleStudio, AssessmentStudio } from "./course-architect";
import { BlueprintControls, QuickCheckStudio } from "./learning-studio";
import { VoiceInput } from "./voice-input";
import { compilerJobs, nextCompilerJob, defaultInputs, validateInputs, compilerIssues, type CompilerInputs } from "@/lib/novalearn/course-compiler";
import { learningConfig } from "@/lib/novalearn/learning-domain";
import { chunkText, type Course } from "@/lib/novalearn/course-domain";

const steps=["Professor inputs","AI blueprint","Module generation","Assessment design","Review & refine","Finalize & export"];
const guidance=[
  "Start with the course identity, your semester constraints and what students should be able to do. Add a topic outline; reference materials are optional. I preserve your existing modules and work. Save inputs, then build the blueprint. Voice inserts an editable transcript.",
  "Review my interpretation and the learning outcomes. Every outcome should describe something students can demonstrate. Open the graph editor to adjust concepts and prerequisites. The planner checks their order; you remain the academic authority.",
  "Run the weekly planner and module generators. Each module gets teaching notes, guided practice, application, a diagnostic, an assignment and a Teach Nova activity. Completed stages are saved. Pause takes effect after the current request, and Resume skips completed work.",
  "Map checkpoints and the integrated final, then review the prompts and rubric criteria. Assignments and Teach Nova belong to each module. Checkpoints test explanation and application; the final asks students to solve and defend a realistic problem.",
  "Read the drafts before approving them. Check factual claims, source citations, quiz answer keys, rubric weights, prerequisites and workload. Resolve the validation issues below. You can edit individual materials without regenerating the entire course.",
  "Choose which modules students can access, preview the course package, then publish an approved version. The current student release stays unchanged until you publish. Export the professor package or print to PDF; LMS synchronization is not connected.",
];

export function CourseCompiler(){
  const w=useWorkspace(),d=w.course.data,c=d.compiler;
  const [step,setStep]=useState(0),[running,setRunning]=useState(false),[active,setActive]=useState(""),[failure,setFailure]=useState(""),[inputs,setInputs]=useState<CompilerInputs>(c?.inputs||defaultInputs(d)),[outline,setOutline]=useState(d.syllabus),[title,setTitle]=useState(w.course.title),[published,setPublished]=useState(false);
  const stop=useRef(false),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{stop.current=true;mounted.current=false;};},[]);
  useEffect(()=>{setInputs(w.course.data.compiler?.inputs||defaultInputs(w.course.data));setOutline(w.course.data.syllabus);setTitle(w.course.title);setStep(0);setPublished(false);setFailure("");},[w.course.id]);
  const set=<K extends keyof CompilerInputs>(key:K,value:CompilerInputs[K])=>setInputs(old=>({...old,[key]:value}));
  const jobs=compilerJobs(d),next=nextCompilerJob(d),issues=compilerIssues(d),errors=issues.filter(x=>x.level==="error");
  const done=(key:string)=>!!c?.log.some(l=>l.key===key&&l.status==="complete");
  async function saveInputs(){await w.run(async()=>{
    const parsed=validateInputs(inputs);
    if(title.trim().length<3)throw new Error("Enter a course title.");
    if(outline.trim().length<20)throw new Error("Enter a topic outline with at least 20 characters.");
    if(d.modules.length&&d.modules.length!==parsed.moduleCount)throw new Error(`Your existing course has ${d.modules.length} modules. Match this count or edit the graph; existing modules will not be replaced.`);
    const changed=JSON.stringify(c?.inputs)!==JSON.stringify(parsed)||outline!==d.syllabus;
    if(changed&&c?.log.length&&!window.confirm("Update constraints and reset pipeline checks? Existing materials, assessments and student releases will be preserved. Review existing content against the new intent."))return;
    await w.save({...w.course,title:title.trim(),data:{...d,syllabus:outline,compiler:changed?{inputs:parsed,sourceMap:[],schedule:[],log:[],reviewed:false}:c!}});
    setStep(1);w.notice("Professor inputs saved. Existing content is preserved.");
  });}
  async function runGroup(group:string){
    if(running||w.busy)return;stop.current=false;setRunning(true);setFailure("");
    await w.run(async()=>{
      let current=await w.save();
      try{
        for(let n=0;n<40;n++){
          const job=nextCompilerJob(current.data);
          if(!job||job.group!==group||stop.current)break;
          if(mounted.current)setActive(job.key);
          current=await w.call("compiler-step",{courseId:current.id,version:current.version,key:job.key});
          if(mounted.current)w.setCourse(current);
        }
        if(!stop.current)w.notice(`${group} stages saved. Review the results before continuing.`);
      }catch(e){if(mounted.current)setFailure((e as Error).message);throw e;}
      finally{await w.reload();}
    });
    if(mounted.current){setRunning(false);setActive("");}
  }
  async function retryPlanner(){await w.run(async()=>{await w.save({...w.course,data:{...d,compiler:{...c!,reviewed:false,log:c!.log.filter(l=>!["planner","assessments","validator"].includes(l.key))}}});setStep(2);w.notice("Planner and downstream validation reset. Existing content is kept.");});}
  const approved=()=>w.run(async()=>{const saved=await w.save(w.course,true);w.notice(`Graph approved at revision ${saved.data.revision}.`);});
  const stageButton=(group:string)=><div className="compiler-run-actions"><button className="primary" disabled={running||w.busy||!c||next?.group!==group} onClick={()=>runGroup(group)}><Play size={17}/>{failure?"Retry / resume":`Run ${group.toLowerCase()} stages`}</button>{running&&<button className="secondary" onClick={()=>{stop.current=true;w.notice("Pausing after this request finishes; completed stages will remain saved.");}}><Pause size={17}/>Pause after this stage</button>}<span className="fine">{next?`Next: ${next.name}`:"All generation stages saved"}</span></div>;
  return <div className="compiler">
    <div className="compiler-heading"><div><span className="eyebrow">COURSE COMPILER</span><h2>{steps[step]}</h2><p>From your teaching intent to a reviewed, ready-to-release course.</p></div><Badge>Step {step+1} of 6</Badge></div>
    <nav className="compiler-stepper" aria-label="Course compiler stages">{steps.map((label,n)=><button key={label} aria-current={step===n?"step":undefined} disabled={running||w.busy||(n>0&&!c)} onClick={()=>setStep(n)}><span>{n+1}</span>{label}</button>)}</nav>
    {w.preview&&<p className="compiler-preview-note">Explore mode uses labeled example templates, not live AI. Your preview edits last for this browser session. Live accounts save stages to Supabase.</p>}
    <div className="compiler-layout"><fieldset className="compiler-main course-content-fieldset" disabled={running||w.busy}>
      {failure&&<div className="course-error" role="alert">{failure} Completed stages are safe. Fix the issue and resume.</div>}
      {step===0&&<Panel><h3>Tell Nova about your course</h3><fieldset disabled={running||w.busy} className="course-content-fieldset"><div className="course-form-grid">
        <label>Course title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></label><label>Course code<input placeholder="e.g. ENVS 101" value={inputs.code} onChange={e=>set("code",e.target.value)} maxLength={40}/></label>
        <Select label="Course level" value={inputs.level} onChange={v=>set("level",v as CompilerInputs["level"])} options={["Introductory","Intermediate","Advanced","Graduate"].map(value=>({value,label:value}))}/>
        {([['weeks','Semester weeks',1,52],['hoursPerWeek','Weekly contact hours',.5,40],['moduleCount','Number of modules',1,12],['checkpointCount','Checkpoints, including final',1,8]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step={key==="hoursPerWeek"?.5:1} value={inputs[key]} onChange={e=>set(key,Number(e.target.value))}/></label>)}
        <label>Semester start (optional)<input type="date" value={inputs.startDate} onChange={e=>set("startDate",e.target.value)}/></label>
        <label>Break weeks (comma-separated)<input placeholder="e.g. 8, 14" defaultValue={inputs.breakWeeks.join(", ")} key={w.course.id} onBlur={e=>set("breakWeeks",e.target.value.trim()?e.target.value.split(",").map(x=>Number(x.trim())):[])}/></label>
      </div><label>Prior knowledge / prerequisites<textarea value={inputs.prerequisites} onChange={e=>set("prerequisites",e.target.value)} placeholder="What should students already know?" rows={2}/></label>
      <label>Rough syllabus / topic outline<textarea value={outline} onChange={e=>setOutline(e.target.value)} rows={6} placeholder="One topic per line. Add required topics, scope and exclusions."/></label>
      <label>Professor intent<textarea value={inputs.intent} onChange={e=>set("intent",e.target.value)} rows={4} placeholder="By the end, students should be able to…" maxLength={4000}/></label>
      <VoiceInput label="professor intent" onTranscript={text=>set("intent",(inputs.intent+"\n"+text).trim().slice(0,4000))}/>
      <h4>Grading category weights</h4><div className="compiler-weights">{(["assignments","checkpoints","final"] as const).map(key=><label key={key}>{key} %<input type="number" min={0} max={100} value={inputs.assessmentWeights[key]} onChange={e=>set("assessmentWeights",{...inputs.assessmentWeights,[key]:Number(e.target.value)})}/></label>)}</div><p className="fine">Weights define the course plan, not automatic grades. Teach Nova and mini-quizzes are formative. Checkpoint count includes one final project.</p>
      <button className="primary" onClick={saveInputs}>Save inputs & continue <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setStep(1)}>Open existing graph & sources without compiling</button></fieldset></Panel>}
      {step===1&&<><Panel><h3>Interpretation & learning outcomes</h3>{stageButton("Blueprint")}{c?.intent?<><blockquote>{c.intent.summary}</blockquote><ul>{c.intent.priorities.map(p=><li key={p}>{p}</li>)}</ul></>:<p>Run the blueprint stages to interpret your intent, parse approved materials and check constraints.</p>}
        {d.objectives.map((o,n)=><label key={o.id}>{n+1}. {o.level}<input disabled={running||w.busy} value={o.title} onChange={e=>w.change({objectives:d.objectives.map(x=>x.id===o.id?{...x,title:e.target.value}:x),graphApproved:false})}/></label>)}
        <div className="compiler-stats"><span><Clock/> {(c?.inputs.weeks||0)-(c?.inputs.breakWeeks.length||0)} teaching weeks</span><span>{((c?.inputs.weeks||0)-(c?.inputs.breakWeeks.length||0))*(c?.inputs.hoursPerWeek||0)} contact hours</span><span>{d.modules.length} modules</span></div>
        <button className="secondary" disabled={running||w.busy||!d.modules.length} onClick={()=>w.run(async()=>{await w.save();w.notice("Blueprint edits saved.");})}>Save outcome edits</button></Panel>
        <Panel><h3>Reference materials</h3><p>Upload searchable PDF or text. Inspect and approve sources in the editor below before generating grounded content. Unapproved sources are never used.</p><input aria-label="Upload compiler source" type="file" accept=".pdf,.txt,.md,.csv" disabled={running||w.busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;w.run(async()=>{const text=await readDocument(file),id=uid();await w.save({...w.course,data:{...d,sources:[...d.sources,{id,name:file.name,text,approved:false,chunks:chunkText(text,id)}]}});w.notice("Source uploaded as unapproved. Review and approve it in the graph and sources editor.");});e.target.value="";}}/>{done("sources")&&<button className="secondary" disabled={running||w.busy} onClick={()=>w.run(async()=>{await w.save({...w.course,data:{...d,compiler:{...c!,reviewed:false,log:c!.log.filter(l=>!["sources","validator"].includes(l.key))}}});w.notice("Source inventory reset. Run blueprint stages to refresh it; existing content is preserved.");})}>Refresh approved source index</button>}{c?.sourceMap.map(s=><p key={s.sourceId}>{s.name} · {s.chunks} chunks · {s.characters.toLocaleString()} characters</p>)}</Panel>
        <details className="compiler-editor"><summary>Edit graph, prerequisites, sources & class link</summary><Architect/><BlueprintControls defaultTab="graph"/></details>
      </>}
      {step===2&&<><Panel><h3>The generation pipeline</h3>{stageButton("Modules")}<div className="compiler-pipeline">{jobs.filter(j=>j.group!=="Review").map(j=><div key={j.key} className={active===j.key?"processing":done(j.key)?"completed":""}><span className="compiler-job-icon">{done(j.key)?<Check size={16}/>:active===j.key?<Sparkles size={16}/>:<BookOpen size={16}/>}</span><strong>{j.name}</strong><Badge>{active===j.key?"Processing":done(j.key)?"Saved":"Waiting"}</Badge></div>)}</div></Panel>
        <Panel><h3>Course map & time budget</h3>{c?.schedule.length?<><div className="compiler-timeline">{Array.from({length:c.inputs.weeks},(_,n)=>n+1).map(week=>{const slot=c.schedule.find(s=>s.weeks.includes(week));return <div key={week} className={!slot?"break":""}><b>W{week}</b><span>{slot?`M${c.schedule.indexOf(slot)+1}`:"Break"}</span>{slot?.checkpoint&&week===Math.max(...slot.weeks)&&<small>Checkpoint</small>}</div>;})}</div>{c.schedule.map((s,n)=>{const m=d.modules.find(m=>m.id===s.moduleId);if(!m)return null;return <details key={m.id} className="compiler-module" open={n===0}><summary><b>{n+1}. {m.title}</b><span>Week {s.weeks.join(", ")} · {s.hours} hours</span></summary><div className="course-form-grid"><div><h4>Concepts</h4><ul>{m.concepts.map(x=><li key={x}>{x}</li>)}</ul><h4>Prerequisites</h4><p>{m.prerequisites.map(id=>d.modules.find(x=>x.id===id)?.title).join(" → ")||"Entry-level module"}</p></div><div><h4>Learning outcomes</h4><ul>{d.objectives.filter(o=>m.objectiveIds.includes(o.id)).map(o=><li key={o.id}>{o.title}</li>)}</ul><p>{d.materials.filter(x=>x.moduleId===m.id).length} teaching assets · {learningConfig(d).activities.filter(x=>x.moduleId===m.id).length} mini-quizzes</p></div></div><button className="secondary" onClick={()=>{w.setModuleId(m.id);w.navigate("modules");}}>Edit this module</button></details>;})}<p><strong>{c.schedule.reduce((n,s)=>n+s.hours,0)} total contact hours.</strong> Break weeks receive no teaching time.</p></>:<p>The weekly planner allocates your actual teaching weeks and orders prerequisites before dependent modules.</p>}<button className="secondary" disabled={running||w.busy||!done("planner")} onClick={retryPlanner}>Recalculate schedule after edits</button></Panel></>}
      {step===3&&<><Panel><h3>Authentic assessment plan</h3>{stageButton("Assessments")}<div className="compiler-stats">{["Assignment","Checkpoint","Final project","Teach Nova"].map(cat=><span key={cat}><b>{d.checkpoints.filter(x=>x.category===cat).length}</b>{cat}</span>)}</div><p>Rubrics describe observable understanding. AI produces drafts; only the professor approves them.</p>{d.checkpoints.map(cp=><details key={cp.id} className="compiler-module"><summary><b>{cp.title}</b><Badge>{cp.category||"Existing assessment"}</Badge></summary><p>{cp.prompt}</p><p>Aligned outcomes: {cp.objectiveIds.join(", ")} · {cp.points||100} points · {cp.dueAt||"No date set"}</p><dl>{cp.rubric.map((r,n)=><div key={n}><dt><b>{r.criterion} ({r.weight}%)</b></dt><dd>{r.descriptor}</dd></div>)}</dl><p><b>Oral follow-up:</b> {cp.followupStrategy}</p><p><b>Transfer:</b> {cp.transferPrompt}</p></details>)}</Panel><details className="compiler-editor"><summary>Edit assessments, dates & rubrics</summary><AssessmentStudio/></details></>}
      {step===4&&<><Panel><h3>Professor review</h3>{stageButton("Review")}<p>Open each editor, inspect the generated content, then approve individual materials, answer keys and assessments. There is no automatic blanket approval.</p><div className="course-actions"><button className="secondary" disabled={running||w.busy||!d.modules.length} onClick={approved}><ShieldCheck size={16}/>Approve reviewed graph</button><button className="secondary" onClick={()=>setStep(2)}>Review schedule</button></div><label className="compiler-check"><input type="checkbox" checked={!!c?.reviewed} disabled={running||w.busy||!done("validator")} onChange={e=>w.change({compiler:{...c!,reviewed:e.target.checked}})}/>I reviewed the curriculum, workload, factual claims, quiz keys and assessment alignment.</label><button className="primary" disabled={running||w.busy} onClick={()=>w.run(async()=>{await w.save();w.notice("Review acknowledgment saved.");})}>Save review</button></Panel>
        <details className="compiler-editor"><summary>Review teaching notes, guided practice & applied examples</summary><ModuleStudio/></details><details className="compiler-editor"><summary>Review mini-quizzes and answer keys</summary><QuickCheckStudio/></details><details className="compiler-editor"><summary>Review assignments, Teach Nova, checkpoints & final</summary><AssessmentStudio/></details><Validation issues={issues}/></>}
      {step===5&&<><Panel><div className="compiler-success"><ShieldCheck/><div><h3>{errors.length?"Your course is ready for final checks":"Your course package is ready"}</h3><p>{errors.length?`${errors.length} required review items remain.`:"All required checks pass. Choose release modules below."}</p></div></div><h3>{w.course.title}</h3><p>{c?.inputs.code} · {c?.inputs.level} · {c?.inputs.weeks} weeks · {c?.inputs.hoursPerWeek} weekly contact hours</p><div className="compiler-stats"><span>{d.modules.length} modules</span><span>{d.objectives.length} outcomes</span><span>{d.checkpoints.length} assessments</span><span>{d.materials.length} teaching assets</span></div><details><summary>Preview complete professor course package</summary><CourseReport course={w.course}/></details><div className="course-actions"><button className="primary" disabled={running||w.busy||!!errors.length||!!next||!w.course.class_id} onClick={()=>w.run(async()=>{const saved=await w.save();await w.call("release",{courseId:saved.id});setPublished(true);w.notice("Approved course version published. Students see only your selected modules.");})}>Publish to course</button><button className="secondary" onClick={()=>window.print()}><Download size={16}/>Print / Save PDF</button><button className="secondary" onClick={()=>exportJson(`${c?.inputs.code||"course"}-professor-package.json`,{...w.course,data:{...d,sources:d.sources.map(s=>({...s,chunks:s.chunks.map(({vector,...x})=>x)}))}})}>Export JSON package</button><button className="secondary" disabled={running||w.busy} onClick={()=>w.run(async()=>{const saved=await w.save();await w.call("duplicate",{courseId:saved.id});await w.reload();w.notice("Reusable course copy saved. It contains no student records and is not released.");})}>Save as template</button></div>{published&&<p role="status">This approved version has been published.</p>}{!w.course.class_id&&<p className="course-error">Link a class in the blueprint’s graph editor before publishing.</p>}<p className="fine">PDF uses your browser’s print dialog. JSON is a portable professor package, not an LMS import format. Direct Canvas / Blackboard sync is not connected.</p></Panel><BlueprintControls defaultTab="release"/><Validation issues={issues}/></>}
      <div className="compiler-footer"><button className="secondary" disabled={step===0||running||w.busy} onClick={()=>setStep(step-1)}>Back</button>{step>0&&step<5&&<button className="primary" disabled={running||w.busy} onClick={()=>setStep(step+1)}>Continue to {steps[step+1]}<ArrowRight size={16}/></button>}</div>
    </fieldset><aside className="compiler-assistant">{running&&<button className="secondary" onClick={()=>{stop.current=true;w.notice("Pausing after the current stage is safely saved.");}}><Pause size={17}/>Pause compilation</button>}<Nova text={guidance[step]} mode={running?"thinking":published?"celebrating":"idle"}/><Panel><h4>Professor stays in control</h4><ul><li>Existing content is preserved.</li><li>Completed stages are saved.</li><li>Sources require your approval.</li><li>Publishing is always explicit.</li></ul>{active&&<p role="status">Working on: {jobs.find(j=>j.key===active)?.name}</p>}</Panel><details className="compiler-log"><summary>Saved stage history</summary>{c?.log.map(l=><p key={l.key}><b>{l.key}</b> · {(l.ms/1000).toFixed(1)}s<br/>{l.routing}<br/>{l.detail}</p>)}</details></aside></div>
    {step===5&&typeof document!=="undefined"&&createPortal(<div id="nova-course-print"><CourseReport course={w.course}/></div>,document.body)}
  </div>;
}
function Validation({issues}:{issues:ReturnType<typeof compilerIssues>}){return <Panel><h3>Validation & readiness</h3>{issues.length?issues.map((x,n)=><p key={n} className={x.level==="error"?"compiler-issue":"compiler-warning"}><Badge tone={x.level==="error"?"red":"amber"}>{x.level==="error"?"Required":"Review"}</Badge> {x.text}</p>):<p>All required checks passed.</p>}</Panel>;}
function CourseReport({course}:{course:Course}){const d=course.data,c=d.compiler;return <article className="compiler-report"><h1>{course.title}</h1><p>Professor package · draft revision {d.revision} · {c?.inputs.code}</p><p>{c?.inputs.intent}</p><h2>Learning outcomes</h2><ol>{d.objectives.map(o=><li key={o.id}>{o.title} ({o.level})</li>)}</ol><h2>Grading plan</h2><p>Assignments {c?.inputs.assessmentWeights.assignments}% · Checkpoints {c?.inputs.assessmentWeights.checkpoints}% · Final {c?.inputs.assessmentWeights.final}%</p>{d.modules.map(m=><section key={m.id}><h2>{m.title}</h2><p>Weeks {c?.schedule.find(s=>s.moduleId===m.id)?.weeks.join(", ")||m.week} · Concepts: {m.concepts.join(", ")}</p>{d.materials.filter(x=>x.moduleId===m.id).map(x=><div key={x.id}><h3>{x.title} — {x.approved?"Approved":"Draft"}</h3><p className="prewrap">{x.content}</p></div>)}{learningConfig(d).activities.filter(x=>x.moduleId===m.id).map(q=><div key={q.id}><h3>{q.title}</h3><p>{q.question}</p><ol>{q.options.map((o,n)=><li key={n}>{o}</li>)}</ol><p>Professor key: {q.answer===undefined?"Not set":q.options[q.answer]}. {q.explanation}</p></div>)}{d.checkpoints.filter(x=>x.moduleId===m.id).map(a=><div key={a.id}><h3>{a.title}</h3><p>{a.prompt}</p><ul>{a.rubric.map((r,n)=><li key={n}>{r.criterion} ({r.weight}%) — {r.descriptor}</li>)}</ul><p>Follow-up: {a.followupStrategy}</p><p>Transfer: {a.transferPrompt}</p></div>)}</section>)}<h2>Approved references</h2>{d.sources.filter(s=>s.approved).map(s=><p key={s.id}>{s.name} · {s.id}</p>)}<p>Professor-only package contains answer keys. Do not distribute it as a student handout.</p></article>;}
