"use client";
import { useState } from "react";
import { LockKeyhole, Network, Plus, Save, Send, Sparkles, Trash2 } from "lucide-react";
import { Panel, Badge, Select, useWorkspace, uid, ModuleSelect } from "./course-ui";
import { useLearning } from "./learning-context";
import { learningConfig, validateLearning, type LearningConfig, type Activity } from "@/lib/novalearn/learning-domain";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./ui/tabs";

export function BlueprintControls({defaultTab="intent"}:{defaultTab?:"intent"|"graph"|"release"}={}) {
  const w = useWorkspace(), l = learningConfig(w.course.data), state = useLearning();
  const patch = (p: Partial<LearningConfig>) => w.change({ learning: { ...l, ...p } });
  return <Panel className="blueprint-panel"><div className="section-title"><div><p className="eyebrow">Professor intent → a living course</p><h2><Network size={22} /> Semester blueprint</h2></div><Badge>Draft revision {w.course.version}</Badge></div>
    <Tabs defaultValue={defaultTab}><TabsList><TabsTrigger value="intent">Intent & rhythm</TabsTrigger><TabsTrigger value="graph">Concept graph</TabsTrigger><TabsTrigger value="release">Release controls</TabsTrigger></TabsList>
      <TabsContent value="intent"><div className="learning-three"><label>Semester weeks<input type="number" min={1} max={52} value={l.weeks} onChange={e => patch({ weeks: +e.target.value })} /></label><label>Workload · hours/week<input type="number" min={1} max={40} value={l.hoursPerWeek} onChange={e => patch({ hoursPerWeek: +e.target.value })} /></label><label>Checkpoint every N modules<input type="number" min={1} max={12} value={l.checkpointEvery} onChange={e => patch({ checkpointEvery: +e.target.value })} /></label></div><label>Teaching intent and constraints<textarea rows={3} value={l.teachingIntent} maxLength={2000} onChange={e => patch({ teachingIntent: e.target.value })} /></label><p className="fine">These constraints guide course generation. Workload is a planning target; Nova does not silently create or publish assessments. External research is off: course content uses your approved sources.</p><div className="blueprint-rhythm">{w.course.data.modules.map((m, i) => <div key={m.id}><small>Week {m.week}</small><b>{m.title}</b><span>{(i + 1) % l.checkpointEvery === 0 ? "Applied checkpoint + reflection" : "Teach · practice · quick check"}</span></div>)}</div></TabsContent>
      <TabsContent value="graph"><p>Each concept belongs to a module and shares its learning objectives. Edit prerequisite edges below; cycles are rejected when saved.</p>{l.concepts.map(c => <details className="concept-editor" key={c.id}><summary><Network size={15} /> {c.name} <small>{w.course.data.modules.find(m => m.id === c.moduleId)?.title}</small></summary><label>Concept name<input value={c.name} onChange={e => patch({ concepts: l.concepts.map(x => x.id === c.id ? { ...x, name: e.target.value } : x) })} /></label><p className="fine">Objectives: {c.objectiveIds.map(id => w.course.data.objectives.find(o => o.id === id)?.title).join(" · ")}</p><div className="concept-prereqs">{l.concepts.filter(x => x.id !== c.id).map(p => <label key={p.id}><input type="checkbox" checked={c.prerequisites.includes(p.id)} onChange={e => patch({ concepts: l.concepts.map(x => x.id === c.id ? { ...x, prerequisites: e.target.checked ? [...x.prerequisites, p.id] : x.prerequisites.filter(id => id !== p.id) } : x) })} />{p.name}</label>)}</div></details>)}<button className="secondary" onClick={() => { if (window.confirm("Rebuild concept mappings from the current modules? This clears quick-check drafts in this course draft, not already released activities or submitted evidence.")) w.change({ learning: { ...learningConfig({ ...w.course.data, learning: undefined }), weeks: l.weeks, hoursPerWeek: l.hoursPerWeek, checkpointEvery: l.checkpointEvery, teachingIntent: l.teachingIntent }, graphApproved: false }); }}>Rebuild from module concepts</button></TabsContent>
      <TabsContent value="release"><p>The full roadmap remains visible. Only released modules expose materials, checks, and tutoring. Save + release to apply changes to students.</p><div className="release-grid">{w.course.data.modules.map(m => <label key={m.id}><input type="checkbox" checked={l.releasedModuleIds.includes(m.id)} onChange={e => patch({ releasedModuleIds: e.target.checked ? [...l.releasedModuleIds, m.id] : l.releasedModuleIds.filter(id => id !== m.id) })} /><span><b>{m.title}</b><small>Week {m.week} · {l.releasedModuleIds.includes(m.id) ? "Selected for release" : "Locked"}</small></span><LockKeyhole size={17} /></label>)}</div><h3>Source access scope</h3><p className="fine">A source is exposed only when ALL its assigned modules are released. Unscoped sources require every module to be released. Assign sources carefully: Nova cannot redact future topics inside a document.</p>{w.course.data.sources.map(s => <div className="source-scope" key={s.id}><b>{s.name}</b><div className="concept-prereqs">{w.course.data.modules.map(m => <label key={m.id}><input type="checkbox" checked={s.moduleIds?.includes(m.id) || false} onChange={e => w.change({ sources: w.course.data.sources.map(x => x.id === s.id ? { ...x, moduleIds: e.target.checked ? [...(x.moduleIds || []), m.id] : x.moduleIds?.filter(id => id !== m.id) } : x) })} />{m.title}</label>)}</div></div>)}<h3>Immutable release history</h3>{state.versions.length ? state.versions.map(v => <Badge key={v.version}>v{v.version} · {new Date(v.released_at).toLocaleDateString()}</Badge>) : <p className="fine">No release snapshots yet. Your first release will create one.</p>}</TabsContent>
    </Tabs><div className="course-actions"><button className="secondary" onClick={() => w.run(async () => { const data = { ...w.course.data, learning: l }; validateLearning(data); await w.save({ ...w.course, data }); w.notice("Blueprint draft saved."); })}><Save size={16} /> Save blueprint</button><button className="primary" disabled={!w.course.data.graphApproved} onClick={() => w.run(async () => { const data = { ...w.course.data, learning: l }; validateLearning(data); const c = await w.save({ ...w.course, data }); await w.call("release", { courseId: c.id }); await state.refresh(); w.notice("Versioned course release saved. Students can access selected modules."); })}><Send size={16} /> Save + release selected modules</button></div></Panel>;
}

export function QuickCheckStudio() {
  const w = useWorkspace(), l = learningConfig(w.course.data), concepts = l.concepts.filter(c => c.moduleId === w.moduleId);
  const [active, setActive] = useState("");
  const a = l.activities.find(a => a.id === active && a.moduleId === w.moduleId);
  const patch = (p: Partial<Activity>) => w.change({ learning: { ...l, activities: l.activities.map(x => x.id === a?.id ? { ...x, ...p } : x) } });
  return <Panel><div className="section-title"><div><p className="eyebrow">Understand early. Intervene sooner.</p><h2>Quick checks & live pulse</h2><p>Small, low-stakes checks with a confidence rating and explanation.</p></div><Badge>{l.activities.length} activities</Badge></div><ModuleSelect /><div className="course-actions">{l.activities.filter(a => a.moduleId === w.moduleId).map(a => <button className={a.id === active ? "primary" : "secondary"} key={a.id} onClick={() => setActive(a.id)}>{a.title}</button>)}<button className="secondary" disabled={!concepts.length} onClick={() => { const id = uid("check"); w.change({ learning: { ...l, activities: [...l.activities, { id, moduleId: w.moduleId, title: "New concept check", kind: "Pulse check", question: "Explain which option best fits this scenario.", options: ["First option", "Second option", "Third option"], answer: 0, explanation: "", conceptIds: [concepts[0].id], difficulty: "Core", approved: false, sourceIds: [] }] } }); setActive(id); }}><Plus size={16} /> New check</button><button className="secondary" disabled={!concepts.length} onClick={() => w.run(async () => { const c = await w.save(); const result = await w.call("quick-check", { courseId: c.id, moduleId: w.moduleId }); const next = { ...learningConfig(c.data), activities: [...learningConfig(c.data).activities, result] }; w.change({ learning: next }); setActive(result.id); w.notice("Draft ready. Verify the key, explanation, and source before approving."); })}><Sparkles size={16} /> Draft from sources</button></div>
    {a ? <div className="activity-editor"><div className="course-form-grid"><label>Title<input value={a.title} maxLength={200} onChange={e => patch({ title: e.target.value })} /></label><Select label="Check type" value={a.kind} onChange={kind => patch({ kind: kind as Activity["kind"] })} options={["Diagnostic", "Pulse check", "Exit ticket", "Practice", "Spaced review"].map(x => ({ value: x, label: x }))} /></div><label>Question<textarea rows={3} value={a.question} onChange={e => patch({ question: e.target.value })} /></label><p className="fine">Select the correct answer. Keys and explanations are never sent with the student question.</p>{a.options.map((o, i) => <div className="answer-editor" key={i}><input aria-label={`Correct option ${i + 1}`} type="radio" name={`key-${a.id}`} checked={a.answer === i} onChange={() => patch({ answer: i })} /><input aria-label={`Option ${i + 1}`} value={o} onChange={e => patch({ options: a.options.map((x, j) => i === j ? e.target.value : x) })} /></div>)}<label>Feedback and rationale<textarea rows={3} value={a.explanation} onChange={e => patch({ explanation: e.target.value })} /></label><Select label="Difficulty" value={a.difficulty} onChange={v => patch({ difficulty: v as Activity["difficulty"] })} options={["Foundation", "Core", "Challenge"].map(v => ({ value: v, label: v }))} /><div className="concept-prereqs">{concepts.map(c => <label key={c.id}><input type="checkbox" checked={a.conceptIds.includes(c.id)} onChange={e => patch({ conceptIds: e.target.checked ? [...a.conceptIds, c.id] : a.conceptIds.filter(id => id !== c.id) })} />{c.name}</label>)}</div><label className="check"><input type="checkbox" checked={a.approved} onChange={e => patch({ approved: e.target.checked })} /> I reviewed the question, answer key, concept mapping, and feedback.</label><div className="course-actions"><button className="primary" onClick={() => w.run(async () => { validateLearning(w.course.data); await w.save(); w.notice("Quick check saved. Release the course to share it with students."); })}><Save size={16} /> Save check</button><button className="link" onClick={() => { if (window.confirm("Remove this check from the draft? Existing attempts remain in the evidence history.")) w.change({ learning: { ...l, activities: l.activities.filter(x => x.id !== a.id) } }); }}><Trash2 size={15} /> Remove draft check</button></div></div> : <p className="fine">Select a check above, or create one for this module. Save the graph first if this is a new course.</p>}</Panel>;
}
